"""Original Vietnamese-guided Korean curriculum for electronics workplaces."""
import json,hashlib
from pathlib import Path
RAW='''Hangul: ghép phụ âm và nguyên âm|Hangul ghép chữ thành khối âm tiết: ㄱ + ㅏ = 가. ㅇ ở đầu âm tiết không có âm riêng; ở cuối có âm ng. Âm ㄱ/ㄷ/ㅂ/ㅈ thay đổi theo vị trí; gợi âm Latin chỉ là điểm tựa, hãy nghe mẫu. Học tên chữ và hình chữ qua phần bổ sung từng ngày.|가,ga,âm ga;나,na,âm na;다,da,âm da;라,ra,âm ra;마,ma,âm ma;바,ba,âm ba;사,sa,âm sa;아,a,âm a;자,ja,âm ja;차,cha,âm cha bật hơi;카,ka,âm ka bật hơi;타,ta,âm ta bật hơi|가, 나, 다, 라, 마, 바, 사, 아, 자, 차, 카, 타.|ga na da ra ma ba sa a ja cha ka ta|Luyện đọc từng khối âm tiết, nghe rồi nhắc lại.
Hangul: nguyên âm và phụ âm cuối|ㅓ eo khác ㅗ o; ㅜ u khác ㅡ eu. 받침 là phụ âm cuối khối âm tiết; nhiều phụ âm cuối quy về 7 âm cuối. Khi gặp nguyên âm ở âm tiết sau thường nối âm: 한국어 nghe gần han-gu-geo. Âm căng ㄲ/ㄸ/ㅃ/ㅆ/ㅉ khác âm bật hơi ㅋ/ㅌ/ㅍ/ㅊ.|파,pa,âm pa bật hơi;하,ha,âm ha;어,eo,âm eo;오,o,âm o;우,u,âm u;으,eu,âm eu;이,i,âm i;애,ae,âm ae;에,e,âm e;와,wa,âm wa;위,wi,âm wi;한국어,hangugeo,tiếng Hàn|한국어를 배웁니다.|hangugeoreul baeumnida|Tôi học tiếng Hàn.
Chào hỏi lịch sự|Trong công ty nên bắt đầu bằng lời chào lịch sự. 안녕하세요 dùng phổ biến; 안녕하십니까 trang trọng hơn. 감사합니다 cảm ơn. 안녕히 가세요 nói với người đi; 안녕히 계세요 nói với người ở lại.|안녕하세요,annyeonghaseyo,xin chào;안녕하십니까,annyeonghasimnikka,xin chào trang trọng;감사합니다,gamsahamnida,cảm ơn;죄송합니다,joesonghamnida,xin lỗi;괜찮습니다,gwaenchanseumnida,không sao;네,ne,vâng;아니요,aniyo,không;안녕히 가세요,annyeonghi gaseyo,chào người đi;안녕히 계세요,annyeonghi gyeseyo,chào người ở lại;수고하셨습니다,sugohasyeotseumnida,anh chị đã vất vả rồi;잠시만요,jamsimanyo,xin chờ một chút;부탁드립니다,butakdeurimnida,kính nhờ anh chị|안녕하세요. 잘 부탁드립니다.|annyeonghaseyo jal butakdeurimnida|Xin chào. Mong được anh chị giúp đỡ.
Giới thiệu và chức danh|저는 ...입니다: Tôi là... Dùng 저는 thay 나는 khi nói lịch sự. 씨 dùng sau tên người; 님 thể hiện kính trọng, thường gắn chức danh như 팀장님. Không tự thêm 님 vào tên/chức danh của mình.|저,jeo,tôi lịch sự;이름,ireum,tên;베트남,beteunam,Việt Nam;회사,hoesa,công ty;직원,jigwon,nhân viên;동료,dongnyo,đồng nghiệp;팀장,timjang,trưởng nhóm;부장,bujang,trưởng phòng;사장,sajang,giám đốc công ty;품질팀,pumjiltim,nhóm chất lượng;생산팀,saengsantim,nhóm sản xuất;담당자,damdangja,người phụ trách|저는 루이입니다. 베트남 사람입니다. 품질팀에서 일합니다.|jeoneun ru-i-imnida beteunam saramimnida pumjiltimeseo ilhamnida|Tôi là Louis. Tôi là người Việt Nam. Tôi làm ở nhóm chất lượng.
Số Hán Hàn|일 이 삼... dùng cho ngày tháng, phút, mã số và nhiều số đo. Số 11 là 십일; 20 là 이십. Số điện thoại thường đọc từng chữ số; số 0 đọc 공. Đừng dùng số lượng để thay cách đọc mã linh kiện.|일,il,một Hán Hàn;이,i,hai Hán Hàn;삼,sam,ba Hán Hàn;사,sa,bốn Hán Hàn;오,o,năm Hán Hàn;육,yuk,sáu Hán Hàn;칠,chil,bảy Hán Hàn;팔,pal,tám Hán Hàn;구,gu,chín Hán Hàn;십,sip,mười;백,baek,một trăm;천,cheon,một nghìn|수량은 백 개입니다.|suryangeun baek gaeimnida|Số lượng là 100 cái.
Thời gian và số thuần Hàn|Giờ dùng số thuần Hàn; phút dùng số Hán Hàn. 하나 둘 셋 넷 đổi thành 한 두 세 네 trước lượng từ: 한 개 / 두 시. 30 phút là 삼십 분. 오늘/내일 đặt trước hành động để nói hôm nay/ngày mai.|하나,hana,một thuần Hàn;둘,dul,hai thuần Hàn;셋,set,ba thuần Hàn;넷,net,bốn thuần Hàn;다섯,daseot,năm thuần Hàn;여섯,yeoseot,sáu thuần Hàn;시간,sigan,thời gian / giờ;분,bun,phút;오늘,oneul,hôm nay;내일,naeil,ngày mai;오전,ojeon,buổi sáng / AM;오후,ohu,buổi chiều / PM|오전 아홉 시에 회의를 시작합니다. 매일 삼십 분 공부합니다.|ojeon ahop sie hoeuireul sijakhamnida maeil samsip bun gongbuhamnida|Bắt đầu họp lúc 9 giờ sáng. Tôi học 30 phút mỗi ngày.
Địa điểm và vị trí trong nhà máy|에 diễn đạt đích/vị trí; 에서 thường là nơi hành động xảy ra. 창고에 있습니다: có ở kho. 창고에서 일합니다: làm việc tại kho. 어디에 있습니까？ hỏi ở đâu.|공장,gongjang,nhà máy;사무실,samusil,văn phòng;현장,hyeonjang,hiện trường sản xuất;창고,changgo,kho;검사실,geomsasil,phòng kiểm tra;식당,sikdang,nhà ăn;화장실,hwajangsil,nhà vệ sinh;여기,yeogi,ở đây;저기,jeogi,ở kia;왼쪽,oenjjok,bên trái;오른쪽,oreunjjok,bên phải;어디,eodi,ở đâu|검사실은 어디에 있습니까? 창고 오른쪽에 있습니다.|geomsasileun eodie itseumnikka changgo oreunjjoge itseumnida|Phòng kiểm tra ở đâu? Ở bên phải kho.
Chỉ dẫn và yêu cầu cơ bản|Động từ + 아/어 주세요 là xin hãy làm... 확인해 주세요: hãy kiểm tra giúp. -(으)십시오 trang trọng hơn. Luyện yêu cầu ngắn rõ ràng; tránh nói trống không với đồng nghiệp.|확인하다,hwaginhada,xác nhận / kiểm tra lại;보내다,bonaeda,gửi;받다,batda,nhận;기다리다,gidarida,chờ;시작하다,sijakada,bắt đầu;멈추다,meomchuda,dừng;다시,dasi,lại;먼저,meonjeo,trước tiên;천천히,cheoncheonhi,chậm rãi;빨리,ppalli,nhanh;같이,gachi,cùng nhau;도와주다,dowajuda,giúp đỡ|수량을 확인해 주세요. 결과를 보내 주세요.|suryangeul hwaginhae juseyo gyeolgwareul bonae juseyo|Hãy kiểm tra lại số lượng. Hãy gửi kết quả giúp tôi.
An toàn và ESD|Không hiểu hướng dẫn an toàn thì hỏi lại trước khi thao tác. -지 마세요: xin đừng... 안전모를 착용해 주세요: hãy đội mũ bảo hộ. Từ vựng này giúp giao tiếp; thực hiện quy trình an toàn của nhà máy.|안전,anjeon,an toàn;위험,wiheom,nguy hiểm;주의,juui,chú ý;장갑,janggap,găng tay;보호안경,bohoangyeong,kính bảo hộ;안전화,anjeonhwa,giày bảo hộ;정전기,jeongjeongi,tĩnh điện;접지,jeopji,nối đất;손목밴드,sonmokbaendeu,vòng tay chống tĩnh điện;전원,jeonwon,nguồn điện;비상정지,bisangjeongji,dừng khẩn cấp;착용하다,chagyonghada,mang / đeo bảo hộ|정전기 방지 손목밴드를 착용해 주세요. 전원을 확인해 주세요.|jeongjeongi bangji sonmokbaendeureul chagyonghae juseyo jeonwoneul hwaginhae juseyo|Hãy đeo vòng tay chống tĩnh điện. Hãy kiểm tra nguồn điện.
Linh kiện điện tử|Danh từ + 을/를 đánh dấu đối tượng tác động: 부품을 확인합니다. Sau phụ âm dùng 을; sau nguyên âm dùng 를. Tên linh kiện/mã hàng phải đối chiếu bản vẽ hoặc BOM, không tự suy đoán.|부품,bupum,linh kiện;제품,jepum,sản phẩm;기판,gipan,bo mạch;저항,jeohang,điện trở;콘덴서,kondenseo,tụ điện;커넥터,keonekteo,đầu nối;케이블,keibeul,cáp;안테나,antena,ăng ten;배터리,baeteori,pin;화면,hwamyeon,màn hình;나사,nasa,vít;라벨,rabel,nhãn|기판과 커넥터를 확인해 주세요. 케이블을 연결해 주세요.|gipangwa keonekteoreul hwaginhae juseyo keibeureul yeongyeolhae juseyo|Hãy kiểm tra bo mạch và đầu nối. Hãy nối cáp.
Lắp ráp và công đoạn|Danh từ + 순서대로: theo thứ tự... -고 nối hành động đơn giản: 확인하고 조립합니다. Công đoạn cụ thể phải theo WI thực tế. Đọc câu mẫu rồi thay tên linh kiện bằng linh kiện trên dây chuyền.|조립,jorip,lắp ráp;공정,gongjeong,công đoạn / quá trình;납땜,napttaem,hàn thiếc;도포,dopo,bôi / phủ;체결,chegyeol,siết / lắp chặt;세척,secheok,làm sạch;건조,geonjo,sấy khô;연결,yeongyeol,kết nối;분리,bulli,tách ra;순서,sunseo,thứ tự;작업표준서,jageoppyojunseo,hướng dẫn thao tác WI;작업자,jageopja,người thao tác|작업표준서의 순서대로 조립해 주세요.|jageoppyojunseoui sunseodaero joriphae juseyo|Hãy lắp ráp theo thứ tự trong hướng dẫn thao tác.
Kế hoạch và sản lượng|...은/는 ...입니다 dùng báo cáo ngắn: 생산량은...입니다. 목표는...입니다: mục tiêu là... 수량은...개입니다: số lượng...cái. Luyện đọc số liệu thật nhưng không đưa thông tin mật vào bản ghi chia sẻ.|생산,saengsan,sản xuất;계획,gyehoek,kế hoạch;목표,mokpyo,mục tiêu;생산량,saengsannyang,sản lượng;수량,suryang,số lượng;라인,rain,dây chuyền;주간,jugan,ca ngày / ban ngày;야간,yagan,ca đêm / ban đêm;잔업,janeop,tăng ca;완료,wallyo,hoàn thành;진행,jinhaeng,đang tiến hành;개,gae,cái / lượng từ|오늘 생산 목표는 천 개입니다. 현재 팔백 개를 완료했습니다.|oneul saengsan mokpyoneun cheon gaeimnida hyeonjae palbaek gaereul wallyohaetseumnida|Mục tiêu hôm nay là 1000 cái. Hiện đã hoàn thành 800 cái.
IQC OQC và kiểm tra chất lượng|검사 thường là kiểm tra/inspection, 시험 thường là thử nghiệm/test. 수입검사 là IQC; 출하검사 là kiểm tra trước xuất hàng. 용어 của từng công ty có thể khác; dùng thêm IQC/OQC để rõ ý.|품질,pumjil,chất lượng;검사,geomsa,kiểm tra inspection;수입검사,suipgeomsa,kiểm tra đầu vào IQC;공정검사,gongjeonggeomsa,kiểm tra trong công đoạn;출하검사,chulhageomsa,kiểm tra xuất hàng OQC;전수검사,jeonsugeomsa,kiểm tra 100 phần trăm;샘플링,saempeulling,lấy mẫu;합격,hapgyeok,đạt;불합격,bulhapgyeok,không đạt;기준,gijun,tiêu chuẩn / tiêu chí;판정,panjeong,phán định;검사표,geomsapyo,phiếu kiểm tra|수입검사가 완료되었습니다. 검사 결과는 합격입니다.|suipgeomsaga wallyodoeeotseumnida geomsa gyeolgwaneun hapgyeogimnida|Kiểm tra đầu vào đã hoàn thành. Kết quả kiểm tra là đạt.
Lỗi và ngoại quan|불량 là lỗi/hàng lỗi; 불량품 là sản phẩm lỗi. ...이/가 있습니다 báo có lỗi. ...을 발견했습니다: đã phát hiện... Ghi vị trí và số lượng; không kết luận nguyên nhân khi chưa xác nhận.|불량,bullyang,lỗi / không đạt;외관,oegwan,ngoại quan;스크래치,seukraechi,vết xước;균열,gyunyeol,vết nứt;오염,oyeom,nhiễm bẩn;변색,byeonsaek,đổi màu;파손,pason,hư vỡ;변형,byeonhyeong,biến dạng;누락,nurak,thiếu / bỏ sót;기포,gipo,bọt khí;박리,bangni,bong tách;위치,wichi,vị trí|화면에 균열이 있습니다. 불량품은 분리해 주세요.|hwamyeone gyunyeori itseumnida bullyangpumeun bullihae juseyo|Màn hình có vết nứt. Hãy tách riêng sản phẩm lỗi.
Đo kích thước và dung sai|치수 đo kích thước; 공차 là dung sai. 기준을 벗어났습니다: vượt ra ngoài tiêu chuẩn. Đơn vị và điểm đo phải theo bản vẽ. Số thập phân thường đọc 점: 일 점 이 밀리미터 = 1.2 mm.|측정,cheukjeong,đo;치수,chisu,kích thước;길이,giri,chiều dài;폭,pok,chiều rộng;높이,nopi,chiều cao;두께,dukke,độ dày;공차,gongcha,dung sai;도면,domyeon,bản vẽ;측정기,cheukjeonggi,thiết bị đo;교정,gyojeong,hiệu chuẩn;밀리미터,millimiteo,milimét;측정값,cheukjeonggap,giá trị đo|두께를 측정했습니다. 측정값이 공차를 벗어났습니다.|dukkereul cheukjeonghaetseumnida cheukjeonggapssi gongchareul beoseonatseumnida|Đã đo độ dày. Giá trị đo nằm ngoài dung sai.
RF và kiểm tra chức năng|검사를 실시합니다: thực hiện kiểm tra. 데이터는 ...에 저장했습니다: dữ liệu đã lưu tại... RF data và chức năng có thể khác tiêu chí; ghi rõ model và điều kiện. Tiếng Hàn có từ mượn đọc theo Hangul.|알에프,arepeu,RF đọc tiếng Hàn;주파수,jupasu,tần số;신호,sinho,tín hiệu;통신,tongsin,truyền thông / giao tiếp;연결상태,yeongyeolsangtae,trạng thái kết nối;기능,gineung,chức năng;지그,jigeu,đồ gá jig;데이터,deiteo,dữ liệu;저장,jeojang,lưu;복사,boksa,sao chép;감도,gamdo,độ nhạy;테스트,teseuteu,kiểm tra test|알에프 테스트는 완료했습니다. 데이터를 복사해 주세요.|arepeu teseuteuneun wallyohaetseumnida deiteoreul boksahae juseyo|Đã hoàn thành kiểm tra RF. Hãy sao chép dữ liệu giúp tôi.
Thử độ tin cậy|시험 조건: điều kiện thử nghiệm. ...동안: trong khoảng thời gian... 온도는...도입니다: nhiệt độ là... Không dùng câu mẫu làm tiêu chuẩn thử; lấy điều kiện từ yêu cầu khách hàng đã phê duyệt.|신뢰성,silloeseong,độ tin cậy;시험,siheom,thử nghiệm;조건,jogeon,điều kiện;온도,ondo,nhiệt độ;습도,seupdo,độ ẩm;고온,goon,nhiệt độ cao;저온,jeoon,nhiệt độ thấp;샘플,saempeul,mẫu;시험시간,siheomsigan,thời gian thử;시험장소,siheomjangso,nơi thử;결과,gyeolgwa,kết quả;중단,jungdan,dừng giữa chừng|시험 조건을 확인해 주세요. 시험 결과를 보고하겠습니다.|siheom jogeoneul hwaginhae juseyo siheom gyeolgwareul bogohagetseumnida|Hãy kiểm tra điều kiện thử nghiệm. Tôi sẽ báo cáo kết quả thử.
Vật liệu và phê duyệt|입고되었습니다: đã nhập vào kho. 승인 후: sau khi phê duyệt. 전에: trước khi... 유효기간을 확인해 주세요 yêu cầu kiểm tra hiệu lực. 승인 nghĩa phê duyệt; không đồng nghĩa kiểm tra đạt.|자재,jajae,vật liệu;입고,ipgo,nhập kho;발주,balju,đặt hàng;구매,gumae,mua hàng;승인,seungin,phê duyệt;보류,boryu,tạm giữ / tạm hoãn;반품,banpum,trả hàng;대체품,daechepum,hàng thay thế;로트,roteu,lô lot;유효기간,yuhyogigan,thời hạn hiệu lực;성적서,seongjeokseo,báo cáo kết quả kiểm tra;변경,byeongyeong,thay đổi|자재가 입고되었습니다. 검사와 승인 후 사용해 주세요.|jajaega ipgodoeeotseumnida geomsawa seungin hu sayonghae juseyo|Vật liệu đã nhập kho. Hãy sử dụng sau khi kiểm tra và phê duyệt.
Kho nhãn và truy xuất|표시하다: đánh dấu/ghi nhãn. 로트 번호: số lô. 따로 보관해 주세요: hãy bảo quản riêng. 재고와 기록을 대조합니다: đối chiếu tồn kho với ghi chép. Không tự quyết định MRB nếu chưa có quy trình/ủy quyền.|재고,jaego,tồn kho;보관,bogwan,lưu kho / bảo quản;출고,chulgo,xuất kho;상자,sangja,thùng / hộp;포장,pojang,đóng gói;바코드,bakodeu,mã vạch;번호,beonho,số / mã;표시,pyosi,đánh dấu / ký hiệu;추적,chujeok,truy xuất;이력,iryeok,lịch sử;유통기한,yutonggihan,hạn sử dụng / lưu thông;선입선출,seonipseonchul,nhập trước xuất trước FIFO|상자에 로트 번호를 표시해 주세요. 보류 자재는 따로 보관해 주세요.|sangjae roteu beonhoreul pyosihae juseyo boryu jajaeneun ttaro bogwanhae juseyo|Hãy ghi số lô trên thùng. Hãy lưu riêng vật liệu tạm giữ.
Xuất hàng và giao hàng|출하 xuất hàng từ nhà máy; 납품 giao hàng cho khách hàng. 예정입니다: dự kiến... 지연되었습니다: đã bị chậm. Ngày/giờ và số lượng phải nói rõ để tránh nhầm lẫn.|출하,chulha,xuất hàng;납품,nappum,giao hàng;배송,baesong,vận chuyển giao;납기,napgi,hạn giao hàng;일정,iljeong,lịch trình;지연,jiyeon,chậm trễ;완제품,wanjepum,thành phẩm;포장명세서,pojangmyeongseo,packing list;송장,songjang,hóa đơn / vận đơn theo ngữ cảnh;운송,unsong,vận chuyển;수출,suchul,xuất khẩu;목적지,mokjeokji,nơi đến|출하는 내일 오후에 예정되어 있습니다. 수량과 포장을 확인해 주세요.|chulhaneun naeil ohue yejeongdoeeo itseumnida suryanggwa pojangeul hwaginhae juseyo|Dự kiến xuất hàng chiều mai. Hãy kiểm tra số lượng và đóng gói.
Báo cáo tiến độ và nguyên nhân|...때문에: vì... -(으)ㄹ 예정입니다: dự kiến sẽ... 확인 중입니다: đang xác nhận. Nêu việc đã biết và việc còn chờ; dùng 원인 확인 중 để tránh biến giả thiết thành kết luận.|현재,hyeonjae,hiện tại;상태,sangtae,trạng thái;미완료,miwallyo,chưa hoàn thành;진행률,jinhaengnyul,tỷ lệ tiến độ;문제,munje,vấn đề;원인,wonin,nguyên nhân;대책,daechaek,biện pháp;조치,jochi,hành động xử lý;재작업,jaejageop,làm lại;선별,seonbyeol,sàng lọc;예정,yejeong,dự kiến;긴급,gingeup,khẩn cấp|현재 선별 작업이 진행 중입니다. 원인은 확인 중입니다.|hyeonjae seonbyeol jageobi jinhaeng jungimnida wonineun hwagin jungimnida|Hiện đang sàng lọc. Đang xác nhận nguyên nhân.
Họp và trao đổi|-(으)시겠습니까？ là hỏi lịch sự về ý muốn. 참석해 주시겠습니까？ anh chị có thể tham dự không? hiểu rồi: 이해했습니다. Chưa hiểu: 이해하지 못했습니다. Hãy xin nói lại khi cần.|회의,hoeui,cuộc họp;참석,chamseok,tham dự;안건,angeon,nội dung nghị sự;의견,uigyeon,ý kiến;질문,jilmun,câu hỏi;설명,seolmyeong,giải thích;이해하다,ihaehada,hiểu;동의하다,donguihada,đồng ý;결정,gyeoljeong,quyết định;공유,gongyu,chia sẻ;다음,daeum,tiếp theo;회의록,hoeuirok,biên bản họp|회의는 오전 아홉 시에 시작합니다. 참석해 주시겠습니까?|hoeuineun ojeon ahop sie sijakhamnida chamseokhae jusigetseumnikka|Cuộc họp bắt đầu lúc 9 giờ sáng. Anh chị có thể tham dự không?
Tài liệu báo cáo và ISO|서명 là ký tên; 날인 là đóng dấu. 회사 직인 là con dấu công ty. 검토 후 승인해 주세요: hãy phê duyệt sau khi xem xét. Nói rõ người có quyền ký theo quy định công ty.|보고서,bogoseo,báo cáo;문서,munseo,tài liệu;기록,girok,ghi chép / hồ sơ;서명,seomyeong,chữ ký / ký tên;날인,narin,đóng dấu;직인,jigin,con dấu chính thức;검토,geomto,xem xét;심사,simsa,đánh giá audit;시정조치,sijeongjochi,hành động khắc phục;절차서,jeolchaseo,quy trình;첨부파일,cheombupail,tệp đính kèm;최신본,choesinbon,bản mới nhất|첨부 보고서를 검토해 주세요. 서명과 회사 직인이 필요합니다.|cheombu bogoseoreul geomtohae juseyo seomyeonggwa hoesa jigini piryohamnida|Hãy xem xét báo cáo đính kèm. Cần chữ ký và con dấu công ty.
Nhà cung cấp và khách hàng|지원 요청: yêu cầu hỗ trợ. 회신 부탁드립니다: kính nhờ phản hồi. 교체 가능 수량: số lượng có thể thay thế. Xác nhận lịch và phạm vi hỗ trợ bằng câu rõ ràng, không hứa trước khi được phê duyệt.|공급업체,gonggeubeopche,nhà cung cấp;고객사,gogaeksa,công ty khách hàng;요청,yocheong,yêu cầu;회신,hoesin,phản hồi;지원,jiwon,hỗ trợ;교체,gyoche,thay thế;반환,banhwan,trả lại;방문,bangmun,đến thăm;협의,hyeobui,trao đổi thống nhất;요구사항,yogusahang,yêu cầu cụ thể;견적,gyeonjeok,báo giá;연락,yeollak,liên hệ|불량 수량은 백 개입니다. 교체 가능 수량을 확인하고 회신 부탁드립니다.|bullyang suryangeun baek gaeimnida gyoche ganeung suryangeul hwaginhago hoesin butakdeurimnida|Số lượng lỗi là 100 cái. Kính nhờ xác nhận số lượng có thể thay thế và phản hồi.
Sự cố thiết bị và xin hỗ trợ|...이/가 고장 났습니다: bị hỏng. -아서/어서 nói lý do: 지그가 없어서 측정할 수 없습니다. Không thể đo do thiếu jig là vấn đề điều kiện đo, chưa phải kết luận sản phẩm lỗi.|설비,seolbi,thiết bị sản xuất;고장,gojang,hỏng;수리,suri,sửa chữa;점검,jeomgeom,kiểm tra tình trạng;모터,moteo,động cơ;프로그램,peurogeuraem,chương trình;부족,bujok,thiếu;불가능,bulganeung,không thể;가능,ganeung,có thể;필요하다,piryohada,cần;재확인,jaehwagin,xác nhận lại;해결,haegyeol,giải quyết|지그가 없어서 측정할 수 없습니다. 담당자의 지원이 필요합니다.|jigeuga eopseoseo cheukjeonghal su eopseumnida damdangjaui jiwoni piryohamnida|Không thể đo vì không có jig. Cần người phụ trách hỗ trợ.
Bàn giao và tổng ôn|Ghép thành báo cáo 60–90 giây: tên/nhóm, việc đã làm, kết quả, việc chờ, người phụ trách và hạn hoàn thành. 인계하다 bàn giao, 인수하다 tiếp nhận. Kiểm tra cuối khóa dùng mục học của tất cả các tuần.|인수인계,insu-ingye,bàn giao tiếp nhận;인계하다,ingyehada,bàn giao;인수하다,insuhada,tiếp nhận;업무,eommu,công việc / nhiệm vụ;후임자,huimja,người tiếp nhiệm;인계서,ingyeseo,biên bản bàn giao;교육,gyoyuk,đào tạo;기한,gihan,thời hạn;진척상황,jincheoksanghwang,tình hình tiến độ;미결사항,migyeolsahang,việc chưa giải quyết;책임자,chaegimja,người chịu trách nhiệm;정리하다,jeongnihada,tổng hợp / sắp xếp|미결사항과 기한을 정리했습니다. 담당자에게 업무를 인계하겠습니다.|migyeolsahanggwa gihaneul jeongnihaetseumnida damdangjaege eommureul ingyehagetseumnida|Đã tổng hợp việc chưa giải quyết và thời hạn. Tôi sẽ bàn giao công việc cho người phụ trách.'''
def aid(s):return hashlib.sha256(s.encode()).hexdigest()[:16]
weeks=[]
for row in RAW.splitlines():
 title,note,words,h,p,v=row.split('|')
 vocab=[]
 for x in words.split(';'):
  han,roman,vi=x.split(',');vocab.append(dict(h=han,p=roman,v=vi,a=aid(han)))
 weeks.append(dict(title=title,note=note,words=vocab,sentence=dict(h=h,p=p,v=v,a=aid(h))))
phases=['Từ mới và phát âm','Nghe và phân biệt âm','Từ mới và mẫu câu','Nghe rồi trả lời','Đọc Hangul và luyện viết','Hội thoại và ghi âm','Ôn tập và kiểm tra']
tasks=[
['Ôn 3 mục cũ (tuần đầu: xem cách ghép Hangul).','Học 6 mục đầu, nghe và đọc mỗi mục 3 lần.','Nghe câu mẫu rồi nhắc theo từng cụm.','Tự nói 3 câu; hai tuần đầu đọc âm tiết.','Viết 2 khối Hangul theo hình mẫu.'],
['Che nghĩa và nhớ lại 6 mục đã học.','Đọc ghi chú và chú ý nguyên âm/phụ âm cuối.','Làm kiểm tra nghe trước khi nhìn chữ.','Ghi âm 6 mục và so với giọng mẫu.','Viết 2 khối Hangul, đọc thành tiếng.'],
['Ôn 6 mục đầu không nhìn nghĩa.','Học 6 mục còn lại và cách dùng trong công việc.','Nghe câu mẫu 3 lần, đọc theo từng cụm.','Thay thông tin trong mẫu bằng tên nhóm/vật liệu của mình.','Viết 2 khối Hangul mới.'],
['Ôn đủ 12 mục của tuần.','Đọc câu mẫu và ghi chú cấu trúc.','Nghe không nhìn chữ, kể lại nghĩa tiếng Việt.','Đặt và trả lời 3 câu về chủ đề tuần.','Viết hoặc gõ một câu ngắn.'],
['Đọc Hangul và thử nhớ nghĩa.','Che gợi âm Latin, tự đọc từ và câu mẫu.','Nghe để kiểm tra cách đọc của mình.','Tự nói 3–5 câu về chủ đề.','Viết 2 khối Hangul, so lại hình chữ.'],
['Ôn các mục còn khó.','Soạn hội thoại 4–6 lượt theo tình huống tuần.','Nghe và nhắc lại theo nhịp, chú ý giọng lịch sự.','Ghi âm hội thoại; tự sửa một lỗi phát âm.','Viết một câu từ hội thoại.'],
['Ôn các mục sai trong bài kiểm tra.','Làm kiểm tra đọc và nghe, xem đáp án.','Nghe lại các mục trả lời sai.','Tự báo cáo 30–60 giây; hai tuần đầu đọc âm và từ.','Viết 2 khối Hangul và đánh dấu hoàn thành.']]
days=[dict(day=w*7+d+1,week=w,phase=d,title=phases[d]) for w in range(26) for d in range(7)]
# Seven daily sound drills per introductory week, with literal Hangul to trace.
DRILLS=[
('ㅏ · ㅓ · ㅗ · ㅜ · ㅡ · ㅣ','아, 어, 오, 우, 으, 이.','a eo o u eu i','Nghe 6 nguyên âm. ㅓ và ㅗ khác nhau; ㅡ không đọc như u.'),
('ㄱ · ㄴ · ㄷ · ㄹ · ㅁ','가, 나, 다, 라, 마.','ga na da ra ma','Ghép phụ âm với ㅏ. ㄹ đầu âm tiết gần âm r nhẹ, cuối âm tiết gần l.'),
('ㅂ · ㅅ · ㅇ · ㅈ · ㅎ','바, 사, 아, 자, 하.','ba sa a ja ha','ㅇ đứng đầu không phát âm; đứng cuối thường có âm ng.'),
('ㄱ / ㅋ · ㄷ / ㅌ · ㅂ / ㅍ · ㅈ / ㅊ','가, 카, 다, 타, 바, 파, 자, 차.','ga ka da ta ba pa ja cha','Âm bật hơi ㅋ ㅌ ㅍ ㅊ: đặt tay trước miệng để cảm nhận luồng hơi.'),
('ㄲ · ㄸ · ㅃ · ㅆ · ㅉ','까, 따, 빠, 싸, 짜.','kka tta ppa ssa jja','Âm căng không phải đọc to hơn đơn thuần. Nghe sự khác nhau với âm thường và âm bật hơi.'),
('ㅏ · ㅑ · ㅓ · ㅕ · ㅗ · ㅛ · ㅜ · ㅠ','아, 야, 어, 여, 오, 요, 우, 유.','a ya eo yeo o yo u yu','Thêm nét tạo các nguyên âm có âm y. Đọc chậm từng khối rồi đọc liền.'),
('가 나 다 라 마 바 사 아 자 차 카 타 파 하','가, 나, 다, 라, 마, 바, 사, 아, 자, 차, 카, 타, 파, 하.','ga na da ra ma ba sa a ja cha ka ta pa ha','Ôn đọc không nhìn gợi âm, nhận mặt chữ và tự ghi âm.'),
('ㅐ · ㅔ · ㅘ · ㅝ · ㅟ · ㅢ','애, 에, 와, 워, 위, 의.','ae e wa wo wi ui','Nguyên âm ghép. ㅐ/ㅔ có thể rất gần nhau trong tiếng Hàn hiện đại; 의 thay cách đọc theo vị trí.'),
('ㄱ · ㄴ · ㄷ · ㄹ · ㅁ · ㅂ · ㅇ (받침)','국, 눈, 옷, 달, 밤, 밥, 강.','guk nun ot dal bam bap gang','Phụ âm cuối thường không bật ra thêm nguyên âm. 옷 đọc với âm cuối t, không đọc thành o-seu.'),
('먹어요 · 읽어요 · 한국어','먹어요. 읽어요. 한국어.','meogeoyo ilgeoyo hangugeo','Nối âm với âm tiết sau bắt đầu bằng ㅇ: 먹어요 nghe gần 머거요. 받침 kép cần nghe từ thực tế.'),
('국물 · 입니다 · 합니다','국물. 입니다. 합니다.','gungmul imnida hamnida','Một số âm biến đổi: 국물 nghe gần 궁물; 입니다/합니다 có âm m-n. Gợi âm không thay thế audio.'),
('안녕 · 사람 · 회사','안녕. 사람. 회사.','annyeong saram hoesa','Đọc từng khối âm tiết rồi ghép thành từ. Viết khối gọn trong ô vuông.'),
('안녕하세요 · 감사합니다','안녕하세요. 감사합니다.','annyeonghaseyo gamsahamnida','Nghe cả cụm, nhắc từng phần rồi cả câu. Giọng lịch sự dùng trong công ty.'),
('한국어를 배웁니다','한국어를 배웁니다.','hangugeoreul baeumnida','Kiểm tra hai tuần đầu: đọc Hangul không nhìn Latin; so bản ghi với mẫu.')]
for i,(glyph,h,p,v) in enumerate(DRILLS):days[i]['drill']=dict(glyph=glyph,h=h,p=p,v=v,a=aid(h))
root=Path(__file__).parent
course=dict(weeks=weeks,days=days,tasks=tasks)
(root/'app/src/main/assets/course.json').write_text(json.dumps(course,ensure_ascii=False,indent=2))
assert len(weeks)==26 and len(days)==182
assert all(len(w['words'])==12 for w in weeks)
assert [d['day'] for d in days]==list(range(1,183))
assert all(x['p'].isascii() for w in weeks for x in [*w['words'],w['sentence']]),'Romanization must be Latin'
print('Validated 26 weeks, 182 days,',len({x['h'] for w in weeks for x in w['words']}),'unique vocabulary/sound items')
