"""Original Vietnamese grammar explanations and manufacturing examples.
Each lesson has two contextual examples and two scored cloze questions.
"""
ZH='''Trật tự câu S + V + O|Chủ ngữ + động từ + tân ngữ|Câu kể cơ bản đặt người thực hiện trước hành động, rồi đối tượng. Thời gian thường đứng đầu câu hoặc sau chủ ngữ; không đảo thứ tự theo tiếng Việt một cách máy móc.|Không đặt tân ngữ trước động từ khi chưa học cấu trúc 把 hoặc chủ đề hóa.|我们[检查]产品。~Chúng tôi kiểm tra sản phẩm.~产品~我们|工程师[测量]尺寸。~Kỹ sư đo kích thước.~尺寸~工程师
Là: 是 và danh từ|A 是 B|是 nối chủ ngữ với danh từ nhận diện, nghề hoặc vai trò. Phủ định dùng 不是. Khi mô tả tính chất bằng tính từ thường không cần 是; có thể dùng 很 để câu tự nhiên.|Không nói 产品是很好 cho câu sản phẩm tốt đơn giản.|我是质量[工程师]。~Tôi là kỹ sư chất lượng.~测量~检查|这是[标准]样品。~Đây là mẫu chuẩn.~正在~很
Câu tính từ và 很|Chủ ngữ + 很 + tính từ|很 thường nối chủ ngữ với tính từ trong câu nhận xét trung tính; không nhất thiết mang nghĩa rất mạnh. Khi cần đối chiếu có thể bỏ 很. 太…了 diễn đạt quá mức.|Không luôn dịch 很 thành rất và không thêm 是 trước tính từ trong mẫu cơ bản.|这个问题[很]重要。~Vấn đề này quan trọng.~是~有|这个箱子[太]重了。~Thùng này nặng quá.~在~把
Phủ định 不 và 没|不 + thói quen / ý muốn; 没(有) + việc chưa xảy ra|不 thường phủ định thói quen, hiện tại hoặc ý định. 没(有) phủ định sự xảy ra/hoàn thành của hành động. 没有 còn dùng phủ định sở hữu. Khi phủ định việc đã làm thường bỏ 了.|不检查 là không kiểm tra theo lựa chọn; 没检查 là chưa/đã không kiểm tra lần đó.|昨天我们[没]收到材料。~Hôm qua chúng tôi chưa nhận được vật liệu.~不~别|我[不]同意这个方案。~Tôi không đồng ý phương án này.~没~正在
Câu hỏi có không với 吗|Câu kể + 吗？|Thêm 吗 vào cuối câu kể để hỏi có/không. Giữ nguyên trật tự câu kể. Trả lời bằng động từ hoặc tính từ phù hợp: 是/不是, 有/没有, 可以/不可以.|Không thêm 吗 sau câu đã có 什么/谁/哪里 để hỏi thông tin thông thường.|检查完成了[吗]？~Kiểm tra đã xong chưa?~什么~谁|这个零件合格[吗]？~Linh kiện này đạt không?~哪里~多少
Từ hỏi giữ vị trí thông tin|谁 / 什么 / 哪里 / 多少|Từ hỏi đặt tại vị trí thông tin muốn biết: 谁负责？谁 là người thực hiện. 检查什么？什么 là đối tượng. Không đưa mọi từ hỏi lên đầu câu như tiếng Anh.|Hỏi số lượng phải chỉ rõ vật cần đếm; 多少 có thể dùng cho số lớn.|[谁]负责这个工序？~Ai phụ trách công đoạn này?~哪里~多少|我们需要[多少]个样品？~Chúng ta cần bao nhiêu mẫu?~谁~哪里
Hỏi nối tiếp và chủ đề với 呢|Danh từ / chủ đề + 呢？|呢 dùng hỏi tiếp cùng thông tin đã nói: 我完成了，你呢？ cũng có thể hỏi vị trí trong ngữ cảnh như 报告呢？. 呢 không tự mang một nghĩa cố định tách khỏi ngữ cảnh.|Không dùng 呢 để thay 吗 trong mọi câu hỏi có/không.|我完成了，你[呢]？~Tôi đã xong, còn bạn thì sao?~的~把|我的报告[呢]？~Báo cáo của tôi đâu rồi?~得~被
Sở hữu và định ngữ 的|Người / đặc điểm + 的 + danh từ|的 nối người sở hữu hoặc phần bổ nghĩa với danh từ. Ví dụ 客户的要求 là yêu cầu của khách hàng. Trong một số từ ghép nghề nghiệp như 质量工程师 không dùng 的.|Phân biệt 的 bổ nghĩa danh từ với 得 bổ nghĩa mức độ sau động từ.|这是客户[的]要求。~Đây là yêu cầu của khách hàng.~得~地|请使用最新[的]图纸。~Hãy dùng bản vẽ mới nhất.~得~了
Lượng từ và số lượng|Số + lượng từ + danh từ|Sau số thường cần lượng từ: 三个零件、两张标签、一台机器. 两 thường dùng trước lượng từ cho số hai; 二 dùng số thứ tự và số đếm ghép như 二十.|Không dùng 一个机器 trong bài này: máy thường dùng 台. 个 không thay được mọi lượng từ.|我们需要两[台]机器。~Chúng ta cần hai máy.~张~杯|请打印三[张]标签。~Hãy in ba nhãn.~台~本
Chỉ định 这 / 那|这 / 那 + lượng từ + danh từ|这 chỉ gần, 那 chỉ xa hoặc đã được nhắc. Chỉ nhiều cái dùng 这些/那些 không thêm 个. Có thể nói 这批材料 để chỉ lô vật liệu này.|区分 这台机器 một máy với 这些机器 nhiều máy.|请检查这[批]材料。~Hãy kiểm tra lô vật liệu này.~谁~吗|[这些]零件需要返工。~Những linh kiện này cần làm lại.~这个~哪台
Sở hữu và tồn tại 有|Người / nơi chốn + 有 + vật|有 nói có sở hữu hoặc có vật tồn tại: 仓库里有材料. Phủ định dùng 没有. Không dùng 不有. Câu hỏi có thể dùng 有没有.|在 nhấn vị trí của vật đã biết; 有 giới thiệu sự tồn tại.|仓库里[有]三箱材料。~Trong kho có ba thùng vật liệu.~是~被|我们[没有]备用夹具。~Chúng tôi không có jig dự phòng.~不有~不在
Vị trí 在|Vật / người + 在 + nơi chốn|在 làm động từ vị trí: 材料在仓库里. Nó cũng mở cụm trạng ngữ nơi chốn trước động từ: 在仓库检查材料. Dùng 里/上/下/旁边 để xác định quan hệ không gian.|Không nhầm 在 vị trí với 有 tồn tại.|材料[在]仓库里。~Vật liệu ở trong kho.~有~把|标签在箱子[上]。~Nhãn ở trên thùng.~前~了
Nơi thực hiện hành động|在 + địa điểm + động từ|Cụm 在 + nơi chốn thường đứng trước động từ để nêu nơi thực hiện: 在检验室测量. Người nói có thể đặt thời gian trước cụm nơi chốn.|Không đặt mọi địa điểm sau động từ theo tiếng Việt.|我们[在]检验室测量尺寸。~Chúng tôi đo kích thước trong phòng kiểm tra.~给~从|请[在]这里签名。~Hãy ký tên ở đây.~把~被
Vị trí thời gian trong câu|Thời gian + S + V / S + thời gian + V|Thời gian thường đặt đầu câu hoặc sau chủ ngữ, trước động từ. Thứ tự thông dụng: người + thời gian + nơi + hành động. Ngày/giờ cần nói rõ khi bàn lịch xuất hàng.|Không xem mọi từ thời gian là dấu hiệu bắt buộc của 了; trạng thái tương lai có thể dùng 将/要.|我们[明天]出货。~Ngày mai chúng tôi xuất hàng.~昨天了~已经了|[今天下午]开会。~Chiều nay họp.~明天上午~昨天晚上
Tần suất và phạm vi|常常 / 每天 / 都 / 只|常常 thường xuyên, 每天 mỗi ngày, 都 đều, 只 chỉ. 都 thường đứng sau tập hợp chủ ngữ và trước động từ. 不都 là không phải tất cả; 都不 là tất cả đều không.|Phân biệt 我们不都同意 với 我们都不同意.|这些产品[都]合格。~Những sản phẩm này đều đạt.~只~谁|这台设备[只]用于测试。~Thiết bị này chỉ dùng để thử nghiệm.~都~每
了 sau động từ: hoàn thành|Động từ + 了 + tân ngữ|了 sau động từ đánh dấu hành động đã hoàn thành trong ngữ cảnh, không tương đương mọi thì quá khứ. Có thể đi cùng số lượng: 检查了十个样品. Phủ định bằng 没(有), thường bỏ 了.|Không thêm 了 chỉ vì câu nói về hôm qua; cần xét hành động hay trạng thái.|我们检查[了]十个样品。~Chúng tôi đã kiểm tra mười mẫu.~吗~的|工程师测量[了]厚度。~Kỹ sư đã đo độ dày.~着~把
了 cuối câu: thay đổi tình trạng|Trạng thái / câu + 了|了 cuối câu có thể báo trạng thái mới: 机器好了 máy đã ổn trở lại. 不…了 là không còn... nữa. Câu có thể vừa có hoàn thành vừa có thay đổi tình trạng.|不生产了 là không sản xuất nữa; 没生产 là đã/chưa không sản xuất lần đó.|机器可以用[了]。~Máy đã có thể sử dụng được rồi.~吗~的|我们不使用旧图纸[了]。~Chúng tôi không dùng bản vẽ cũ nữa.~着~过
Trải nghiệm với 过|Động từ + 过|过 chỉ từng trải qua hành động, thường không xác định một lần cụ thể. 没有…过 phủ định trải nghiệm. Có thể hỏi 用过吗？ đã từng dùng chưa?|了 nói lần hoàn thành; 过 nói kinh nghiệm từng có.|我用[过]这种测量仪。~Tôi từng dùng loại máy đo này.~着~的|我没有做[过]这个测试。~Tôi chưa từng làm phép thử này.~了~吗
Đang làm 正在 / 在|正在 / 在 + động từ|正在 nhấn đang diễn ra tại thời điểm nói. Câu kết thúc bằng 呢 có thể làm sắc thái đang diễn ra rõ hơn. Đừng nhầm với 在 làm vị trí; xét từ theo sau.|正在 kiểm tra khác 已经 kiểm tra xong.|我们[正在]检查来料。~Chúng tôi đang kiểm tra vật liệu đầu vào.~已经~曾经|机器[正在]运行。~Máy đang vận hành.~已经~还没
Trạng thái duy trì 着|Động từ + 着|着 thường miêu tả trạng thái duy trì sau một hành động như 门开着 cửa đang mở. Không dùng với mọi hành động đang xảy ra; 正在 phù hợp hơn cho hành động tiến hành.|门开着 là cửa ở trạng thái mở, không nhất thiết ai đó đang mở cửa.|门开[着]。~Cửa đang mở.~过~把|箱子上贴[着]标签。~Trên thùng đang có nhãn dán.~吗~过
会 / 能 / 可以|Kỹ năng / khả năng điều kiện / được phép|会 thường nói kỹ năng đã học; 能 khả năng do điều kiện; 可以 sự cho phép hoặc khả năng phù hợp. Chúng có vùng nghĩa giao nhau nhưng cần chọn theo ý định trong công việc.|我会操作 nói biết cách vận hành; 我可以操作 có thể nói được phép vận hành.|我[会]操作这台设备。~Tôi biết cách vận hành thiết bị này.~正在~已经|批准以后才[可以]使用。~Chỉ sau khi phê duyệt mới được sử dụng.~正在~了
想 và 要|想 + động từ / 要 + vật hoặc hành động|想 diễn đạt muốn/nghĩ, thường mềm hơn; 要 có thể thể hiện muốn lấy, yêu cầu hoặc sắp làm. Trong yêu cầu lịch sự dùng 请/想请 để tránh giọng mệnh lệnh.|我要… có thể mạnh; trao đổi với khách hàng nên chọn sắc thái phù hợp.|我[想]确认交货日期。~Tôi muốn xác nhận ngày giao hàng.~被~把|我们[要]增加两个样品。~Chúng ta cần tăng thêm hai mẫu.~在~着
Phải và cần 必须 / 需要|必须 + động từ; 需要 + vật / hành động|必须 nhấn bắt buộc; 需要 nói nhu cầu. 不必/不需要 là không cần; 不能/不可以 là không được hoặc không thể. Không đánh đồng không cần với cấm.|必须检查 không có nghĩa chỉ có khả năng kiểm tra; đó là yêu cầu bắt buộc.|使用前[必须]检查。~Trước khi dùng bắt buộc kiểm tra.~可能~也许|我们[需要]新的夹具。~Chúng tôi cần jig mới.~正在~已经
Cấm và nhắc nhở 别 / 不要|别 / 不要 + động từ|别/不要 diễn đạt đừng làm. Văn bản an toàn dùng 禁止 + hành động hoặc 严禁. Lời nhắc phải rõ đối tượng và hành động; không dùng câu luyện học làm quy trình an toàn.|不要操作 nói đừng thao tác; 不需要操作 là không cần thao tác.|[不要]使用不合格材料。~Đừng sử dụng vật liệu không đạt.~不需要~已经|[别]忘记保存数据。~Đừng quên lưu dữ liệu.~没~了
Yêu cầu lịch sự 请 / 一下|请 + động từ; động từ + 一下|请 thể hiện xin hãy. 一下 làm hành động ngắn hoặc lời nhờ mềm hơn. 请帮我… nhờ người khác giúp mình. Với việc dài, 一下 là phép lịch sự chứ không cam kết chỉ vài giây.|Không cần thêm 您 ở mọi vị trí; vẫn giữ câu rõ ràng và lịch sự.|[请]确认数量。~Xin hãy xác nhận số lượng.~被~把|请检查[一下]这个问题。~Xin kiểm tra giúp vấn đề này.~什么~过
Thứ tự thao tác 先…再…|先 + bước 1，再 + bước 2|先 và 再 nói thứ tự thực hiện trong tương lai hoặc quy trình. 然后 sau đó nối bước kế tiếp. 再 thường là lại/lần sau; 又 thường là lại với việc đã xảy ra.|Không dùng 又 thay 再 trong chỉ dẫn bước cần thực hiện tiếp.|[先]检查，再入库。~Trước tiên kiểm tra rồi nhập kho.~又~最|请确认后[再]出货。~Hãy xác nhận xong rồi xuất hàng.~又~已经
Nguyên nhân 因为…所以…|因为 lý do，所以 kết quả|Có thể dùng cả 因为 và 所以, hoặc lược một phần khi quan hệ rõ. Nêu nguyên nhân đã xác nhận; nếu chưa biết, nói 原因还在调查中.|Đừng dùng nguyên nhân suy đoán như kết luận chắc chắn.|[因为]设备故障，所以停机了。~Vì thiết bị hỏng nên đã dừng máy.~虽然~如果|材料还没到，[所以]无法生产。~Vật liệu chưa đến nên không thể sản xuất.~但是~而且
Điều kiện 如果…就…|如果 điều kiện，就 kết quả|Nếu điều kiện đáp ứng thì xảy ra kết quả. Trong kế hoạch công việc nêu rõ điều kiện được xác nhận, không hứa kết quả vô điều kiện. 就 nhấn quan hệ điều kiện/kết quả.|Nếu là điều kiện cần duy nhất dùng 只有…才…; không tự thay bằng 如果.|[如果]检查合格，就可以出货。~Nếu kiểm tra đạt thì có thể xuất hàng.~虽然~因为|如果缺料，[就]通知采购。~Nếu thiếu vật liệu thì thông báo bộ phận mua hàng.~却~但
Nhượng bộ 虽然…但是…|虽然 tình huống，但是 điều đối lập|Mẫu nêu hai ý tương phản, như đã sửa nhưng cần xác nhận lại. Có thể lược 但是 trong một số câu. 与 因为…所以… khác ở quan hệ đối lập so với nguyên nhân.|Đừng nối 虽然 với 所以 để tạo câu đối lập.|[虽然]设备修好了，但是还要验证。~Mặc dù thiết bị đã sửa xong nhưng vẫn cần kiểm chứng.~因为~如果|虽然数量不多，[但是]必须检查。~Mặc dù số lượng ít nhưng vẫn phải kiểm tra.~所以~就
So sánh 比|A 比 B + tính từ|比 giới thiệu đối tượng so sánh; tính từ theo sau thường không thêm 很. Có thể thêm 一点儿/多了 để nói mức chênh. Số liệu đo nên dùng chênh lệch cụ thể.|Không nói A比B很大 theo mẫu cơ bản.|这批材料[比]上一批厚。~Lô vật liệu này dày hơn lô trước.~把~被|这个箱子比那个箱子重[一点儿]。~Thùng này nặng hơn thùng kia một chút.~很~是
So sánh không bằng 没有|A 没有 B + tính từ|没有 trong cấu trúc này nghĩa không bằng, không phải không sở hữu. 不比 nói không hơn, không luôn đồng nghĩa kém hơn. Dùng số liệu nếu cần kết luận kỹ thuật.|A不比B高 không khẳng định A thấp hơn B; có thể bằng.|这台机器[没有]那台快。~Máy này không nhanh bằng máy kia.~比~把|这批产品没有上批[重]。~Lô sản phẩm này không nặng bằng lô trước.~是~在
Hơn và nhất 更 / 最|更 + tính từ; 最 + tính từ|更 nói mức hơn so với một mốc; 最 nói mức cao nhất trong phạm vi. Phải xác định phạm vi trong báo cáo như 本周最高. Không dùng 最 để thay số liệu đo.|最重要 không tự là mức ưu tiên được công ty phê duyệt; đó là nhận xét ngôn ngữ.|这个方法[更]简单。~Phương pháp này đơn giản hơn.~把~被|这是[最]重要的问题。~Đây là vấn đề quan trọng nhất.~了~着
Bổ ngữ kết quả 完 / 好 / 到|Động từ + kết quả|检查完 kiểm tra xong, 修好 sửa ổn, 找到 tìm thấy. Kết quả đứng sau động từ. Không chỉ nói đã làm mà cần phân biệt việc đã hoàn thành/kết quả đạt.|修了 có thể chỉ đã sửa; 修好了 nhấn đã sửa xong và ổn.|我们检查[完]了。~Chúng tôi đã kiểm tra xong.~吗~的|工程师已经修[好]了机器。~Kỹ sư đã sửa máy ổn rồi.~吗~呢
Bổ ngữ mức độ 得|Động từ + 得 + nhận xét|得 đứng sau động từ để nói mức/cách thực hiện: 做得很好. Khi động từ có tân ngữ thường lặp động từ hoặc chuyển tân ngữ thành chủ đề. 的 bổ nghĩa danh từ, 地 mở trạng ngữ trước động từ.|别 nhầm 做得快 với 快速地做; trật tự khác nhau.|他做[得]很好。~Anh ấy làm rất tốt.~的~地|这个零件装[得]不太好。~Linh kiện này được lắp chưa tốt lắm.~的~地
Bổ ngữ khả năng 得 / 不|Động từ + 得/不 + kết quả|看得懂 đọc hiểu được; 看不懂 đọc không hiểu. Đây là khả năng đạt kết quả trong tình huống, khác 会说 kỹ năng biết nói. Dùng ngắn gọn khi xin giải thích tài liệu.|Không nói 看得不懂; dạng phủ định là 看不懂.|这张图纸我看[不]懂。~Bản vẽ này tôi đọc không hiểu.~得~了|这些标签我看[得]清楚。~Những nhãn này tôi đọc rõ được.~不~过
把: xử lý một đối tượng xác định|S + 把 + đối tượng + V + kết quả/nơi|把 đưa đối tượng đã biết lên trước động từ, nhấn xử lý làm nó thay đổi hoặc chuyển vị trí. Sau động từ thường cần kết quả, nơi đến hoặc yếu tố bổ sung. Không dùng với mọi động từ như 是/有.|Không viết chỉ 我把产品检查; dùng 我把产品检查完了.|请[把]不良品分开放。~Hãy để riêng sản phẩm lỗi.~被~是|请把报告[发给]客户。~Hãy gửi báo cáo cho khách hàng.~在~有
被: thể bị động|Đối tượng + 被 + tác nhân + hành động|被 nhấn đối tượng chịu hành động, thường có kết quả. Có thể lược tác nhân khi không biết. Trong báo cáo trung tính còn dùng 已完成/已批准 tùy ngữ cảnh.|Không bắt buộc dùng 被 cho mọi câu bị động tiếng Việt; tránh làm câu báo cáo nặng nề.|标签[被]贴错了。~Nhãn đã bị dán sai.~把~在|电缆被夹[坏]了。~Cáp đã bị kẹp hỏng.~的~吗
Phạm vi 从…到…|从 điểm bắt đầu 到 điểm kết thúc|Dùng cho nơi, thời gian hoặc giai đoạn: 从九点到十点. 到 còn diễn đạt đến nơi/kết quả. Báo cáo phải nói rõ đơn vị ngày/giờ để tránh hiểu sai.|Không dùng 给 thay 到 trong cấu trúc phạm vi.|会议[从]九点开始。~Cuộc họp bắt đầu từ 9 giờ.~给~被|从入库[到]出货都要记录。~Từ nhập kho đến xuất hàng đều phải ghi chép.~给~把
Đối tượng giao tiếp 给 / 对 / 跟|给 người + vật; 对 đối tượng; 跟 người|给 thường là cho hoặc hướng người nhận; 对 giới thiệu đối tượng thái độ/hành động; 跟 thường là với/đi cùng. Không hoán đổi máy móc khi dịch từ với tiếng Việt.|联系客户 thường trực tiếp, không bắt buộc dùng 跟 trong mọi câu liên hệ.|请把数据发[给]我。~Hãy gửi dữ liệu cho tôi.~从~到|请[跟]工程师确认。~Hãy xác nhận với kỹ sư.~被~把
Vừa…vừa… 一边…一边…|一边 hành động 1，一边 hành động 2|Nói hai hành động cùng diễn ra, thường có cùng người thực hiện. Chỉ dùng khi thực tế hai hành động có thể cùng làm. Không áp dụng cho thao tác cần tập trung hoặc quy trình không cho phép.|Không dùng mẫu để chỉ bước tuần tự; bước tuần tự dùng 先…再….|他[一边]检查，一边记录。~Anh ấy vừa kiểm tra vừa ghi chép.~先~因为|我们一边讨论，[一边]修改报告。~Chúng tôi vừa thảo luận vừa sửa báo cáo.~所以~然后'''

KO='''Chủ đề 은/는 và trật tự SOV|Chủ đề + đối tượng + động từ|Tiếng Hàn thường đặt động từ cuối câu. 은 sau phụ âm cuối, 는 sau nguyên âm; chúng nêu chủ đề hoặc đối chiếu. Có thể lược chủ ngữ khi đã rõ nhưng cần giữ rõ người chịu trách nhiệm trong báo cáo.|Đừng đặt động từ giữa câu theo trật tự tiếng Việt. 은/는 không thay 이/가 trong mọi tình huống.|저[는] 품질팀 직원입니다.~Tôi là nhân viên nhóm chất lượng.~은~을|이 제품[은] 합격입니다.~Sản phẩm này thì đạt.~는~를
Chủ ngữ 이/가|Danh từ + 이/가|이 sau phụ âm cuối; 가 sau nguyên âm. Thường đánh dấu chủ ngữ, thông tin mới hoặc phần cần nhấn. 은/는 thiên về chủ đề và đối chiếu. Không chỉ chọn theo nghĩa tiếng Việt mà phải xét phụ âm cuối.|제품 kết thúc bằng phụ âm ㅁ nên 제품이; 자재 kết thúc bằng nguyên âm nên 자재가.|제품[이] 도착했습니다.~Sản phẩm đã đến.~가~를|자재[가] 부족합니다.~Vật liệu thiếu.~이~을
Tân ngữ 을/를|Đối tượng + 을/를 + động từ|을 sau phụ âm cuối, 를 sau nguyên âm. Đánh dấu đối tượng của hành động như 검사하다/확인하다. Trong hội thoại có thể lược nhưng khi học/báo cáo nên dùng rõ.|Không nhầm sản phẩm là chủ thể 도착하다 với sản phẩm là đối tượng 검사하다.|제품[을] 검사합니다.~Tôi kiểm tra sản phẩm.~를~가|자재[를] 확인해 주세요.~Hãy kiểm tra vật liệu giúp tôi.~을~이
Là: 입니다 / 이에요 / 예요|Danh từ + 입니다; phụ âm + 이에요 / nguyên âm + 예요|입니다 trang trọng; 이에요/예요 lịch sự trong hội thoại. Sau phụ âm cuối dùng 이에요, sau nguyên âm dùng 예요. Phủ định danh từ dùng 이/가 아닙니다 hoặc 아니에요.|아니에요 viết như vậy, không phải 아니예요. Không thêm 입니다 sau mọi tính từ.|저는 검사원[입니다].~Tôi là nhân viên kiểm tra, giọng trang trọng.~있습니다~갑니다|이것은 지그[예요].~Đây là jig, giọng hội thoại lịch sự.~이에요~없어요
Có và không có 있습니다 / 없습니다|Nơi + 에 + vật + 이/가 있습니다|있다 nói tồn tại/sở hữu; 없다 phủ định. Khi nói có vật ở đâu dùng nơi + 에. Câu thao tác dùng 에서 cho nơi xảy ra hành động; không dùng 에서 thay 에 trong mẫu tồn tại cơ bản.|Không dịch có thành 입니다; 입니다 là là.|창고에 자재가 [있습니다].~Trong kho có vật liệu.~입니다~갑니다|예비 지그가 [없습니다].~Không có jig dự phòng.~아닙니다~합니다
Nơi chốn 에 và 에서|에: vị trí/đích; 에서: nơi thực hiện|창고에 있다 là có ở kho; 창고에서 검사하다 là kiểm tra tại kho. 에 còn đánh dấu đích đi đến hoặc thời điểm. Một số động từ/ngữ cảnh có khác biệt, bắt đầu bằng các mẫu này.|Đừng dùng 창고에 검사합니다 để nói kiểm tra tại kho.|창고[에서] 검사합니다.~Tôi kiểm tra ở kho.~에~를|자재는 창고[에] 있습니다.~Vật liệu ở kho.~에서~을
Giờ và lượng từ|한/두/세/네 + lượng từ; số Hán Hàn + 분|Giờ dùng số thuần Hàn; phút dùng số Hán Hàn. 하나 둘 셋 넷 đổi thành 한 두 세 네 trước nhiều lượng từ. Số đo/mã hàng thường dùng Hán Hàn, không tự đổi hệ số theo tiếng Việt.|두 시 là 2 giờ; 이 분 là 2 phút. 하나 개 phải đổi thành 한 개.|샘플 [두] 개가 필요합니다.~Cần hai mẫu.~둘~이|오전 아홉 시 [삼십] 분에 시작합니다.~Bắt đầu lúc 9 giờ 30 sáng.~서른~세
Đuôi hội thoại lịch sự 아요/어요|Thân có ㅏ/ㅗ + 아요; còn lại + 어요; 하다 → 해요|Đây là đuôi lịch sự thông dụng. Các nguyên âm có thể rút gọn: 보다→봐요, 주다→줘요. Với động từ bất quy tắc cần học dạng cụ thể thay vì áp quy tắc cứng.|하다 thành 해요, không phải 하어요. Dùng nhất quán mức lịch sự trong một trao đổi.|수량을 [확인해요].~Tôi kiểm tra số lượng, giọng hội thoại lịch sự.~확인하어요~확인하다|도면을 [봐요].~Tôi xem bản vẽ, giọng hội thoại lịch sự.~보아요요~보다
Đuôi báo cáo ㅂ니다/습니다|Nguyên âm + ㅂ니다; phụ âm + 습니다|Đuôi trang trọng dùng trong báo cáo, họp và email. 하다→합니다, 있다→있습니다. Động từ có ㄹ cuối bỏ ㄹ trước ㅂ như 만들다→만듭니다. Câu tính từ cũng chia đuôi này.|Không cộng 습니다 vào nguyên mẫu có 다. Loại 다 trước khi chia.|지금 [검사합니다].~Bây giờ tôi kiểm tra, giọng trang trọng.~검사하다습니다~검사하니다|창고에 [있습니다].~Có ở kho, giọng trang trọng.~있니다~있다습니다
Câu hỏi trang trọng ㅂ니까/습니까|Nguyên âm + ㅂ니까？ phụ âm + 습니까？|Dùng hỏi lịch sự trang trọng. 하다→합니까; 있다→있습니까. Không dùng cùng đuôi kể 입니다 trong một câu hỏi cơ bản. Khi hỏi tên/đồ vật với 이다 dùng 입니까.|확인합니까 hỏi có kiểm tra không; 확인합니다 là câu kể.|검사가 완료되었[습니까]?~Kiểm tra đã hoàn thành chưa?~습니다~어요다|이것은 표준 샘플[입니까]?~Đây có phải mẫu chuẩn không?~입니다~있습니다
Quá khứ 았/었/했|Thân + 았/었 + đuôi lịch sự|Theo nguyên âm thân thường chọn 았 cho ㅏ/ㅗ, 었 cho phần còn lại; 하다→했. Ngữ cảnh và từ thời gian giúp xác định quá khứ. 보고했습니다 đã báo cáo, 완료되었습니다 đã hoàn thành.|했어요/했습니다 khác 해요/합니다; không chỉ thêm 어제 mà bỏ chia quá khứ khi ý cần hoàn thành.|어제 검사를 [완료했습니다].~Hôm qua tôi đã hoàn thành kiểm tra.~완료합니다~완료하겠습니다|보고서를 [보냈습니다].~Tôi đã gửi báo cáo.~보냅니다~보내겠습니다
Kế hoạch và ý định 겠 / 예정|겠: ý định/dự đoán; (으)ㄹ 예정: dự kiến|Trong báo cáo của bản thân 하겠습니다 thường là tôi sẽ làm. 예정입니다 nêu kế hoạch dự kiến. 겠 cũng có nghĩa phỏng đoán theo ngữ cảnh, không phải mọi thì tương lai.|Đừng hứa 확실히 nếu lịch chưa được xác nhận. 예정 là dự kiến, không đảm bảo.|내일 결과를 [보고하겠습니다].~Ngày mai tôi sẽ báo cáo kết quả.~보고했습니다~보고합니다|내일 출하할 [예정입니다].~Dự kiến ngày mai xuất hàng.~완료했습니다~끝났습니다
Phủ định ngắn 안 và 못|안 + hành động/tính chất; 못 + không thể làm|안 thường nói không làm hoặc phủ định; 못 nói không thể do khả năng/điều kiện. Với danh từ하다 có thể đặt sau danh từ: 검사 안 해요. 안 phải viết tách từ phía sau.|못 검사해요 không kiểm tra được; 안 검사해요 không kiểm tra theo lựa chọn.|지그가 없어서 측정[을 못 합니다].~Không có jig nên không đo được.~을 했습니다~을 하겠습니다|오늘은 잔업을 [안 합니다].~Hôm nay không tăng ca.~못 했습니다~했습니다
Phủ định dài 지 않다 / 지 못하다|Thân + 지 않다 / 지 못하다|Dạng dài giúp phủ định rõ trong báo cáo. 하지 않습니다 không làm; 하지 못했습니다 đã không thể làm. Với tính từ thường dùng 지 않다. Kết hợp thời gian/điều kiện để tránh hiểu nhầm trách nhiệm.|Không thay 안/못 tùy ý: không thể có lý do điều kiện, còn không làm có thể là lựa chọn.|아직 검사를 완료하지 [못했습니다].~Chưa thể hoàn thành kiểm tra.~않겠습니다~않습니다|이 방법은 어렵지 [않습니다].~Phương pháp này không khó.~못합니다~마세요
Kính ngữ chủ thể (으)시 và yêu cầu 세요|Thân + (으)시 + đuôi; (으)세요|시 tôn trọng người thực hiện hành động, không tự tôn trọng bản thân. -(으)세요 thường yêu cầu lịch sự hoặc nói người được kính trọng. Động từ ㄹ cuối bỏ ㄹ trước 시.|Không dùng 제가 하시겠습니다 cho hành động của mình. Với việc của mình dùng 하겠습니다.|팀장님께서 확인하[십니다].~Trưởng nhóm kiểm tra, có kính ngữ.~다시~는다|팀장님께서 [오십니다].~Trưởng nhóm đến, có kính ngữ.~옵니다시~오다세요
Nhờ làm giúp 아/어 주세요|Thân + 아/어 주세요|Cấu trúc nhờ người khác làm hành động giúp. 확인하다→확인해 주세요; 보내다→보내 주세요. 주세요 có sắc thái yêu cầu lịch sự, phù hợp trao đổi hằng ngày.|드리다 thường khi mình làm cho người khác; 주세요 nhờ người khác làm cho mình.|수량을 [확인해 주세요].~Hãy kiểm tra số lượng giúp tôi.~확인해 드릴게요~확인했습니다|자료를 [보내 주세요].~Hãy gửi tài liệu giúp tôi.~보내 드립니다~받았습니다
Nhờ trang trọng 아/어 주시겠습니까|Thân + 아/어 주시겠습니까？|Dùng hỏi người khác có thể làm giúp không, lịch sự hơn yêu cầu ngắn. 확인해 주시겠습니까 phù hợp email/họp. Không cần dùng dạng rất dài cho mọi trao đổi, nhưng không bỏ kính ngữ khi cần.|주세요 và 주시겠습니까 đều nhờ người khác; 드리겠습니다 là mình sẽ làm cho họ.|보고서를 검토해 [주시겠습니까]?~Anh chị có thể xem xét báo cáo giúp tôi không?~드리겠습니다~주었습니다|회의에 참석해 [주시겠습니까]?~Anh chị có thể tham dự họp không?~드릴까요~했습니다
Cấm làm 지 마세요|Thân + 지 마세요|Diễn đạt xin đừng làm hành động. Văn bản cấm trang trọng có thể dùng 금지. Để nói không cần làm dùng 하지 않아도 됩니다, không phải 하지 마세요.|Không dùng mẫu cấm để nói không cần; hai ý khác nhau.|불량 자재를 사용하지 [마세요].~Đừng sử dụng vật liệu lỗi.~않아도 됩니다~않았습니다|검사 기록을 삭제하지 [마세요].~Đừng xóa hồ sơ kiểm tra.~못했습니다~않아도 됩니다
Điều kiện (으)면|Phụ âm + 으면; nguyên âm + 면|Nếu/khi điều kiện đáp ứng thì thực hiện kết quả. 있다→있으면, 완료하다→완료하면. Động từ ㄹ cuối thường thêm 면 trực tiếp. Nêu điều kiện rõ trong giao tiếp chất lượng.|검사가 끝나면 là khi kiểm tra kết thúc, chưa tự khẳng định đạt.|검사가 완료되[면] 알려 주세요.~Khi kiểm tra hoàn thành hãy báo tôi.~지만~고|문제가 있[으면] 연락해 주세요.~Nếu có vấn đề hãy liên hệ.~면~려고
Lý do 아/어서|Thân + 아/어서 + kết quả|Nối lý do/kết quả hoặc trình tự liên quan. 없다→없어서; 늦다→늦어서. Trong mẫu lý do cơ bản không thường dùng với câu ra lệnh/đề nghị; -(으)니까 phù hợp hơn khi đưa chỉ dẫn.|Lý do nói tình trạng: 지그가 없어서 측정하지 못했습니다; không dùng chỉ vì nguyên mẫu 없다.|지그가 [없어서] 측정하지 못했습니다.~Vì không có jig nên không đo được.~없지만~없으려고|자재가 [늦어서] 생산이 지연되었습니다.~Vì vật liệu đến muộn nên sản xuất chậm.~늦으려고~늦지만
Lý do trong báo cáo 기 때문에|Thân + 기 때문에|Nêu nguyên nhân rõ, tương đối trang trọng. Danh từ + 때문에; động/tính từ + 기 때문에. Có thể kết hợp quá khứ trước 기 nếu cần. Nêu nguyên nhân đã xác nhận, không dùng giả thiết như kết luận.|자재 부족 때문에 là vì thiếu vật liệu; 부족하기 때문에 dùng vị ngữ thiếu.|자재가 부족하[기 때문에] 생산할 수 없습니다.~Vì thiếu vật liệu nên không thể sản xuất.~기 전에~기 위해서|설비 고장 [때문에] 라인이 멈췄습니다.~Vì thiết bị hỏng nên chuyền đã dừng.~전에~후에
Nguyên nhân đưa chỉ dẫn (으)니까|Phụ âm + 으니까; nguyên âm + 니까|-(으)니까 nêu lý do và dùng được với lời nhờ, chỉ dẫn, đề nghị. 춥다→추우니까 có bất quy tắc; 급하다→급하니까. Khác với 아/어서 thường dùng trong câu giải thích kết quả đơn giản.|Chia theo thân và bất quy tắc; đừng gắn 으니까 sau mọi nguyên âm.|급하[니까] 먼저 확인해 주세요.~Vì gấp nên hãy kiểm tra trước.~으니까~려고|문제가 있[으니까] 담당자에게 알려 주세요.~Vì có vấn đề nên hãy báo người phụ trách.~니까~기 전에
Nối hành động 고|Thân + 고 + mệnh đề tiếp|고 nối hai hành động hoặc hai tính chất: 확인하고 기록합니다. Có thể nói thứ tự đơn giản; khi cần nhấn hoàn thành bước trước dùng -(으)ㄴ 후에. Không phải mọi 그리고 đều thay được bằng đuôi 고.|Danh từ dùng 와/과 hoặc 하고 khi liệt kê; động từ dùng thân + 고.|수량을 확인하[고] 기록합니다.~Kiểm tra số lượng và ghi lại.~지만~려고|자재를 받[고] 검사합니다.~Nhận vật liệu rồi kiểm tra.~니까~면서
Sau khi (으)ㄴ 후에|Động từ + (으)ㄴ 후에|Dùng sau khi hành động trước đã hoàn tất: 확인한 후에. Phụ âm thường + 은 후에, nguyên âm + ㄴ 후에; ㄹ cuối biến đổi. Danh từ + 후에 cũng dùng như 검사 후에.|Không dùng 하는 후에 trong mẫu sau khi đã làm. Quy trình cần tiêu chí đạt thì nói 승인 후에.|검사[한 후에] 입고해 주세요.~Sau khi kiểm tra hãy nhập kho.~하기 전에~하면서|자재를 [받은 후에] 검사합니다.~Sau khi nhận vật liệu thì kiểm tra.~받기 전에~받으려고
Trước khi 기 전에|Động từ + 기 전에|Nêu bước phải làm trước một hành động. 기 biến hành động thành danh hóa, không phụ thuộc phụ âm cuối. Với danh từ dùng 전에 trực tiếp như 검사 전에.|Không nhầm 검사 후에 sau kiểm tra với 검사 전에 trước kiểm tra.|사용하[기 전에] 확인해 주세요.~Trước khi dùng hãy kiểm tra.~ㄴ 후에~고 있어서|출하하[기 전에] 포장을 확인합니다.~Trước khi xuất hàng kiểm tra đóng gói.~ㄴ 후에~려고
Đang làm 고 있다|Động từ + 고 있다|Diễn đạt hành động đang tiến hành; có thể chia quá khứ 고 있었습니다. Không dùng với mọi tính từ. 진행 중입니다 là cách báo cáo tương đương ngắn khi nói đang tiến hành.|Đang kiểm tra khác đã kiểm tra xong; 완료했습니다 không thay 검사하고 있습니다.|지금 검사하[고 있습니다].~Bây giờ đang kiểm tra.~고 싶었습니다~겠습니다|불량품을 선별하[고 있습니다].~Đang sàng lọc sản phẩm lỗi.~기 전에 있습니다~ㄴ 후에 있습니다
Trạng thái kết quả 아/어 있다|Động từ phù hợp + 아/어 있다|Nêu trạng thái duy trì sau hành động, thường với động từ không có tân ngữ trực tiếp: 연결되어 있습니다, 붙어 있습니다. 고 있다 thiên về hành động đang diễn ra. Với động từ cụ thể cần học mẫu.|문이 열려 있다 là cửa đang ở trạng thái mở, không phải ai đang mở cửa.|케이블이 연결[되어 있습니다].~Cáp đang ở trạng thái đã kết nối.~하고 있습니다~하려고 합니다|라벨이 [붙어 있습니다].~Nhãn đang dán trên đó.~붙이고 싶습니다~붙이려고 합니다
Có thể (으)ㄹ 수 있다|Thân + (으)ㄹ 수 있다/없다|Khả năng làm do kỹ năng hoặc điều kiện. Phụ âm + 을 수, nguyên âm + ㄹ 수; ㄹ cuối giữ ㄹ. 수 viết tách. 없다 nói không thể. Kèm lý do để làm rõ điều kiện đo.|Không viết 할수 như một từ trong câu chuẩn.|측정할 수 [없습니다].~Không thể đo.~있습니다~있었습니다|이 장비로 검사할 수 [있습니다].~Có thể kiểm tra bằng thiết bị này.~없습니다~없었습니다
Được phép 아/어도 되다|Thân + 아/어도 되다|Nói được phép làm; hỏi ...해도 됩니까？ xin phép. 다 + 도 아니다 không thay được mẫu. Khác 할 수 있다 là có khả năng, không luôn có quyền thao tác.|Có thể thao tác không đồng nghĩa được phép thao tác; phải hỏi quyền/quy trình thực tế.|이 자재를 사용해도 [됩니까]?~Tôi có được phép dùng vật liệu này không?~수 있습니까~했습니다|승인 후에 사용해도 [됩니다].~Sau phê duyệt thì được phép dùng.~없습니다~않습니다
Không được phép (으)면 안 되다|Thân + (으)면 안 되다|Cấu trúc cấm hoặc không được phép. 안 되다 viết tách. 하지 않아도 되다 là không cần làm, không phải cấm. Dùng mẫu rõ khi nói quy định công ty.|Mẫu cấm không thay cho không thể do máy hỏng; khi không thể dùng 할 수 없다.|불량품을 출하하면 [안 됩니다].~Không được xuất hàng lỗi.~됩니다~완료됩니다|기록을 삭제하면 [안 됩니다].~Không được xóa hồ sơ.~됩니다~있습니다
Bắt buộc 아/어야 하다|Thân + 아/어야 하다/되다|Nói cần/phải thực hiện hành động. 하다→해야 합니다; 확인하다→확인해야 합니다. Không cần phải dùng 하지 않아도 됩니다. Đây là mẫu ngôn ngữ, yêu cầu thực tế vẫn theo WI.|Không nhầm 해야 합니다 phải làm với 해도 됩니다 được làm.|사용 전에 확인[해야 합니다].~Trước khi dùng phải kiểm tra.~해도 됩니다~하지 않아도 됩니다|검사 결과를 기록[해야 합니다].~Phải ghi kết quả kiểm tra.~해도 됩니다~하지 않아도 됩니다
Đối lập 지만|Thân + 지만|Nối hai ý đối lập: 수량은 적지만 검사가 필요합니다. Danh từ + 이지만. Thời quá khứ có thể xuất hiện trước 지만. Không dùng 지만 để nêu nguyên nhân đơn thuần.|Thiếu vật liệu gây chậm nên dùng lý do, không dùng đối lập nếu không có ý trái ngược.|수량은 적[지만] 검사가 필요합니다.~Số lượng ít nhưng cần kiểm tra.~어서~기 때문에|수리했[지만] 다시 확인해야 합니다.~Đã sửa nhưng phải kiểm tra lại.~어서~기 때문에
Bối cảnh 는데 / (으)ㄴ데|Động từ + 는데; tính từ + (으)ㄴ데|Nêu bối cảnh, đối lập hoặc dẫn vào câu hỏi/yêu cầu. 있다/없다 dùng 있는데/없는데. Không luôn dịch thành nhưng; xét quan hệ mệnh đề. Danh từ + 인데.|바쁘다 là tính từ → 바쁜데; 확인하다 là động từ → 확인하는데.|지그가 없[는데] 어떻게 측정합니까?~Không có jig thì đo thế nào?~은데~려고|지금 바[쁜데] 나중에 연락하겠습니다.~Bây giờ bận nên lát nữa tôi sẽ liên hệ.~쁘는데~쁘은데
So sánh 보다 / 더 / 가장|A + 보다 + 더 + tính từ|보다 đánh dấu mốc so sánh; 더 nhấn hơn, có thể lược. 가장/제일 nói nhất trong phạm vi. So sánh kỹ thuật cần số liệu thực tế, không dùng tính từ chung thay bằng chứng.|보다 cũng là động từ xem; ngữ pháp so sánh xét vị trí sau danh từ.|이 제품은 이전 제품[보다] 가볍습니다.~Sản phẩm này nhẹ hơn sản phẩm trước.~처럼~만큼|이 문제가 [가장] 중요합니다.~Vấn đề này quan trọng nhất.~조금~같이
Bổ nghĩa danh từ bằng tính từ|Thân tính từ + (으)ㄴ + danh từ|좋다→좋은, 크다→큰. 있다/없다 dùng 있는/없는. Mô tả vật trước danh từ: 불량이 있는 제품. Các bất quy tắc như 어렵다→어려운 cần học riêng.|Không đặt tính từ nguyên mẫu có 다 trước danh từ theo tiếng Việt.|[새로운] 도면을 사용해 주세요.~Hãy dùng bản vẽ mới.~새롭다~새롭는|[큰] 상자에 넣어 주세요.~Hãy cho vào thùng to.~크다~크는
Bổ nghĩa danh từ bằng động từ|Hiện tại 는; quá khứ (으)ㄴ; tương lai (으)ㄹ|검사하는 제품 sản phẩm đang/được kiểm tra theo ngữ cảnh; 검사한 제품 sản phẩm đã kiểm tra; 검사할 제품 sản phẩm sẽ kiểm tra. Đuôi thời gian giúp tránh nhầm trạng thái lô.|Mẫu tương lai không tự khẳng định đã kiểm tra đạt; phải nói kết quả riêng.|검사[한] 제품을 분리해 주세요.~Hãy tách riêng sản phẩm đã kiểm tra.~할~하는|내일 출하[할] 제품입니다.~Đây là sản phẩm sẽ xuất hàng ngày mai.~한~하는
Danh hóa 기|Thân động từ + 기|기 biến hành động thành đơn vị danh từ: 기록하기 việc ghi chép. Có trong 기 전에, 기 때문에 và mục tiêu/công việc. Khi báo cáo dùng danh từ tự nhiên nếu có như 검사/측정.|Không thêm 다 trước 기: 확인하기, không phải 확인하다기.|기록하[기] 전에 확인합니다.~Trước khi ghi chép thì kiểm tra.~다~는|이 장비는 사용하[기] 쉽습니다.~Thiết bị này dễ sử dụng.~다~고
Truyền đạt gián tiếp 다고 하다|Câu kể + 다고 합니다|Tính từ dùng 다고, động từ hiện tại thường ㄴ/는다고, danh từ (이)라고. Quá khứ 았/었다고. Trong báo cáo phải rõ nguồn: 고객이...했다고 합니다. Không biến thông tin nghe lại thành kết luận mình đã kiểm chứng.|완료했다고 합니다 là nghe nói đã hoàn thành, khác mình trực tiếp xác nhận hoàn thành.|고객이 내일 방문한[다고 합니다].~Nghe nói khách hàng ngày mai sẽ đến thăm.~다고 합니까~라고 합니다|검사가 완료되었[다고 합니다].~Nghe nói kiểm tra đã hoàn thành.~라고 합니다~는다고 합니다
Dự định (으)려고 하다|Thân động từ + (으)려고 하다|Nêu ý định sắp làm: 확인하려고 합니다. Phụ âm thường + 으려고; nguyên âm/ㄹ + 려고. Không dùng cho tính từ để tự nói ý định trạng thái. Lịch xác nhận chính thức có thể dùng 예정입니다.|먹으려고 nhưng 가려고; không thêm 으 trước mọi thân nguyên âm.|수량을 확인하[려고 합니다].~Tôi định kiểm tra số lượng.~으려고 합니다~았다고 합니다|보고서를 보내[려고 합니다].~Tôi định gửi báo cáo.~으려고 합니다~었다고 합니다'''

KO += '\nKhiêm nhường 드리다 trong công việc|해 드리다 / 말씀드리다 / 부탁드리다|드리다 thể hiện mình làm việc cho người khác một cách kính trọng. 확인해 드리겠습니다 tôi sẽ kiểm tra giúp anh chị. 주시겠습니까 nhờ người khác giúp mình. Không dùng 드리다 như chủ thể kính ngữ 시.|Phân biệt 부탁드립니다 kính nhờ, với 도와드리겠습니다 tôi sẽ giúp anh chị.|자료를 보내 [드리겠습니다].~Tôi sẽ gửi tài liệu cho anh chị.~주시겠습니까~주세요|확인 후 회신 [부탁드립니다].~Kính nhờ phản hồi sau khi xác nhận.~도와드립니다~보내 드립니다'

def parse(raw):
 lessons=[]
 for idx,line in enumerate(raw.splitlines()):
  title,pattern,explanation,mistake,*examples=line.split('|')
  ex=[];quiz=[]
  for fragment in examples:
   marked,vi,wrong1,wrong2=fragment.split('~');left=marked.index('[');right=marked.index(']');answer=marked[left+1:right];sentence=marked.replace('[','').replace(']','')
   ex.append(dict(h=sentence,p='',v=vi))
   quiz.append(dict(prompt=marked[:left]+' _____ '+marked[right+1:],meaning=vi,answer=answer,options=[answer,wrong1,wrong2],explain=explanation+' Câu đầy đủ: '+sentence+' — '+vi))
  lessons.append(dict(id=idx+1,title=title,pattern=pattern,explanation=explanation,mistake=mistake,examples=ex,quiz=quiz,level='Cơ bản' if idx<15 else 'Ứng dụng' if idx<30 else 'Mở rộng'))
 return lessons
if __name__=='__main__':
 print('Chinese:',len(parse(ZH)),'Korean:',len(parse(KO)))
