"""Original bilingual vocabulary for everyday manufacturing communication.
Lexical entries and meaningful workplace noun phrases, not numbered template sentences.
"""
RAW='''Con người và tổ chức|người=人=사람;nhân viên mới=新员工=신입사원;nhân viên chính thức=正式员工=정규직 직원;nhân viên thời vụ=临时工=임시직 직원;công nhân=工人=근로자;kỹ sư=工程师=엔지니어;kỹ thuật viên=技术员=기술자;quản lý=管理者=관리자;tổ trưởng=组长=조장;quản đốc=车间主任=현장 관리자;phó giám đốc=副总经理=부사장;tổng giám đốc=总经理=대표이사;bộ phận nhân sự=人事部门=인사 부서;bộ phận tài chính=财务部门=재무 부서;bộ phận mua hàng=采购部门=구매 부서;bộ phận kỹ thuật=技术部门=기술 부서;bộ phận bảo trì=维修部门=보전 부서;bộ phận kế hoạch=计划部门=계획 부서;bộ phận kinh doanh=销售部门=영업 부서;nhóm dự án=项目组=프로젝트팀
Quan hệ và phối hợp|đội / nhóm=团队=팀;nhóm trưởng=领班=반장;người liên hệ=联系人=연락 담당자;đồng nghiệp=同事=동료;cấp trên=上级=상사;cấp dưới=下属=부하 직원;trách nhiệm=责任=책임;phân công=分工=업무 분담;hợp tác=合作=협력;phối hợp=配合=협조;hỗ trợ=协助=도움;ủy quyền=授权=위임;thay ca=换班=교대;người thay thế=替代人员=대체 인원;người phê duyệt=审批人=승인자;người kiểm tra=检验员=검사원;người nhận=接收人=수신자;người gửi=发送人=발신자;người lập=编制人=작성자;người phụ trách chính=主要负责人=주 담당자
Thời gian công việc|buổi sáng=早晨=아침;buổi tối=夜晚=저녁;hôm qua=昨天=어제;hôm nay=今天=오늘;ngày mai=明天=내일;ngày kia=后天=모레;tuần này=本周=이번 주;tuần sau=下周=다음 주;tuần trước=上周=지난주;tháng này=本月=이번 달;tháng sau=下个月=다음 달;tháng trước=上个月=지난달;hằng ngày=每天=매일;hằng tuần=每周=매주;hằng tháng=每月=매월;ngay lập tức=立即=즉시;tạm thời=暂时=잠시;trước đó=之前=이전;sau đó=之后=이후;đúng giờ=准时=정시
Ca làm và chấm công|ca sáng=早班=아침 근무;ca chiều=中班=오후 근무;ca đêm=夜班=야간 근무;ca luân phiên=轮班=교대 근무;giờ làm việc=工作时间=근무 시간;giờ nghỉ=休息时间=휴식 시간;nghỉ trưa=午休=점심시간;ngày nghỉ=休息日=휴무일;nghỉ phép=请假=휴가;đi muộn=迟到=지각;về sớm=早退=조퇴;vắng mặt=缺勤=결근;chấm công=考勤=근태 관리;bảng chấm công=考勤表=근태표;quẹt thẻ=刷卡=카드 태그;đi làm=上班=출근;tan làm=下班=퇴근;giờ bắt đầu=开始时间=시작 시간;giờ kết thúc=结束时间=종료 시간;lịch làm việc=排班表=근무표
Nơi làm việc|xưởng=车间=작업장;khu vực=区域=구역;cổng chính=大门=정문;cổng sau=后门=후문;lối vào=入口=입구;lối ra=出口=출구;hành lang=走廊=복도;cầu thang=楼梯=계단;thang máy=电梯=엘리베이터;phòng họp=会议室=회의실;phòng nghỉ=休息室=휴게실;phòng thay đồ=更衣室=탈의실;bãi đỗ xe=停车场=주차장;khu hút thuốc=吸烟区=흡연 구역;khu cách ly=隔离区=격리 구역;khu hàng đạt=合格品区=합격품 구역;khu hàng lỗi=不良品区=불량품 구역;bàn thao tác=工作台=작업대;vị trí làm việc=工位=작업 위치;khu vực sạch=洁净区=청정 구역
Phương hướng và khoảng cách|phía trên=上方=위쪽;phía dưới=下方=아래쪽;phía trước=前方=앞쪽;phía sau=后方=뒤쪽;bên trong=内部=안쪽;bên ngoài=外部=바깥쪽;bên trái=左侧=왼편;bên phải=右侧=오른편;ở giữa=中间=가운데;bên cạnh=旁边=옆;đối diện=对面=맞은편;gần=附近=근처;xa=远处=먼 곳;trên tầng=楼上=위층;dưới tầng=楼下=아래층;hướng=方向=방향;vị trí hiện tại=当前位置=현재 위치;khoảng cách=距离=거리;đường đi=路线=경로;khoảng trống=空隙=틈
Hoạt động thông dụng|mở=打开=열다;đóng=关闭=닫다;lấy=拿取=집다;đặt=放置=놓다;mang đến=拿过来=가져오다;mang đi=拿走=가져가다;đưa cho=递给=건네다;chuyển=转移=옮기다;đổi=更换=바꾸다;tháo=拆下=떼다;lắp=装上=달다;bấm=按=누르다;kéo=拉=당기다;đẩy=推=밀다;xoay=旋转=돌리다;nâng=抬起=들어 올리다;hạ=放下=내리다;giữ=握住=잡다;buông=松开=놓아주다;chạm=触摸=만지다
Trao đổi cơ bản|biết=知道=알다;không biết=不知道=모르다;nhớ=记住=기억하다;quên=忘记=잊다;hiểu=理解=이해하다;nghe=听=듣다;nói=说=말하다;đọc=读=읽다;viết=写=쓰다;hỏi=问=묻다;trả lời=回答=답하다;giải thích=解释=설명하다;thông báo=通知=알리다;nhắc nhở=提醒=상기시키다;xác nhận=确认=확인하다;đồng ý=同意=동의하다;từ chối=拒绝=거절하다;thảo luận=讨论=논의하다;đề nghị=建议=제안하다;liên hệ=联系=연락하다
Trạng thái thông dụng|đúng=正确=정확함;sai=错误=오류;có=有=있다;không có=没有=없다;nhiều=多=많다;ít=少=적다;đủ=足够=충분하다;thiếu=不足=부족하다;tốt=良好=좋다;kém=差=나쁘다;nhanh=快=빠르다;chậm=慢=느리다;mới=新的=새로운;cũ=旧的=오래된;dễ=容易=쉽다;khó=困难=어렵다;giống nhau=相同=같다;khác nhau=不同=다르다;cần thiết=必要=필수;không cần=不需要=불필요
Mức độ và ưu tiên|quan trọng=重要=중요하다;khẩn cấp=紧急=긴급하다;ưu tiên=优先=우선;thông thường=通常=보통;đặc biệt=特殊=특별하다;toàn bộ=全部=전체;một phần=部分=일부;chỉ=仅=오직;thêm=额外=추가;bớt=减少=감소;tăng=增加=증가;liên tục=连续=연속;định kỳ=定期=정기;ngẫu nhiên=随机=무작위;đôi khi=有时=가끔;thường xuyên=经常=자주;chắc chắn=确定=확실하다;có lẽ=可能=아마;rõ ràng=清楚=명확하다;chưa rõ=不清楚=불명확하다
Đơn vị và số liệu|số lượng=数量=수량;số thứ tự=序号=순번;tỷ lệ=比例=비율;phần trăm=百分比=백분율;đơn vị=单位=단위;cái=个=개;bộ=套=세트;chiếc tấm=片=장;thùng=箱=박스;cuộn=卷=롤;túi=袋=봉지;cặp=对=켤레;mét=米=미터;centimét=厘米=센티미터;milimét=毫米=밀리미터;micromét=微米=마이크로미터;gam=克=그램;kilôgam=千克=킬로그램;lít=升=리터;giây=秒=초
Kế hoạch sản xuất|lệnh sản xuất=生产指令=생산 지시;đơn hàng=订单=주문;nhu cầu=需求=수요;năng lực sản xuất=产能=생산 능력;công suất=生产能力=생산 용량;sản lượng=产量=생산량;mục tiêu=目标=목표;dự báo=预测=예측;kế hoạch tháng=月计划=월간 계획;kế hoạch tuần=周计划=주간 계획;kế hoạch ngày=日计划=일일 계획;lịch sản xuất=生产排程=생산 일정;chuyển đổi model=换型=모델 전환;chạy thử=试运行=시운전;sản xuất thử=试产=시험 생산;sản xuất hàng loạt=量产=양산;lô đầu=首批=초도 물량;đơn gấp=急单=긴급 주문;hoàn thành=完成=완료하다;chưa hoàn thành=未完成=미완료
Tiến độ và hiệu suất|tiến độ=进度=진도;tốc độ=速度=속도;hiệu suất=效率=효율;hiệu quả=效果=효과;năng suất=生产率=생산성;thời gian chu kỳ=周期时间=사이클 시간;thời gian chờ=等待时间=대기 시간;thời gian dừng=停机时间=정지 시간;thời gian đổi model=换型时间=모델 전환 시간;chậm tiến độ=进度落后=일정 지연;kịp tiến độ=按期完成=기한 내 완료;tồn công đoạn=在制品=재공품;nút thắt=瓶颈=병목;hao hụt=损耗=손실;lãng phí=浪费=낭비;phân tích=分析=분석;cải tiến=改善=개선;cân bằng chuyền=产线平衡=라인 밸런싱;làm lại=返工=재작업;bổ sung sản lượng=补产=추가 생산
Vật liệu cơ bản|nguyên liệu=原材料=원자재;vật liệu phụ=辅料=부자재;nhựa=塑料=플라스틱;kim loại=金属=금속;thép=钢=강철;thép không gỉ=不锈钢=스테인리스강;nhôm=铝=알루미늄;đồng=铜=구리;niken=镍=니켈;vàng=金=금;bạc=银=은;cao su=橡胶=고무;thủy tinh=玻璃=유리;gốm=陶瓷=세라믹;giấy=纸=종이;bìa carton=纸板=판지;bọt xốp=泡沫=폼;vải=布料=천;keo=胶水=접착제;băng dính=胶带=테이프
Linh kiện và kết cấu|điện trở=电阻=저항기;tụ điện=电容=커패시터;cuộn cảm=电感=인덕터;diode=二极管=다이오드;transistor=晶体管=트랜지스터;chip=芯片=칩;mạch tích hợp=集成电路=집적회로;cảm biến=传感器=센서;công tắc=开关=스위치;cầu chì=保险丝=퓨즈;rơ le=继电器=릴레이;động cơ=电机=모터;đèn LED=发光二极管=엘이디;ổ cắm=插座=소켓;phích cắm=插头=플러그;đầu nối=连接器=커넥터;cáp mềm=排线=플랫 케이블;dây điện=电线=전선;bo mạch in=印刷电路板=인쇄회로기판;bo mạch mềm=柔性电路板=연성 회로기판
Lắp ráp cơ khí|vỏ=外壳=하우징;nắp=盖子=덮개;khung=框架=프레임;giá đỡ=支架=브래킷;miếng đệm=垫片=와셔;lò xo=弹簧=스프링;vít=螺丝=스크루;đai ốc=螺母=너트;bu lông=螺栓=볼트;chốt=销钉=핀;ren=螺纹=나사산;lỗ=孔=구멍;rãnh=槽=홈;bề mặt=表面=표면;cạnh=边缘=가장자리;góc=角=모서리;mối nối=接头=이음부;khe hở=间隙=간격;lực siết=拧紧力=조임 힘;mô men siết=扭矩=토크
Dụng cụ thao tác|tua vít=螺丝刀=드라이버;tua vít điện=电动螺丝刀=전동 드라이버;kìm=钳子=펜치;kìm cắt=剪钳=니퍼;nhíp=镊子=핀셋;dao=刀=칼;kéo=剪刀=가위;búa=锤子=망치;cờ lê=扳手=렌치;lục giác=内六角扳手=육각 렌치;chổi=刷子=브러시;khăn lau=抹布=걸레;máy hút bụi=吸尘器=진공청소기;súng khí=气枪=에어건;súng bắn keo=胶枪=글루건;mỏ hàn=烙铁=인두;băng tải=输送带=컨베이어;khay=托盘=트레이;hộp dụng cụ=工具箱=공구함;dụng cụ=工具=공구
Công đoạn điện tử|gắn linh kiện=贴装=실장;in kem hàn=印刷锡膏=솔더 페이스트 인쇄;hàn reflow=回流焊=리플로 납땜;hàn sóng=波峰焊=웨이브 납땜;hàn tay=手工焊接=수작업 납땜;điểm hàn=焊点=납땜점;kem hàn=锡膏=솔더 페이스트;thiếc hàn=焊锡=납;flux=助焊剂=플럭스;khuôn in=钢网=스텐실;nạp chương trình=烧录=프로그래밍;kiểm tra quang học=光学检测=광학 검사;kiểm tra chức năng=功能测试=기능 검사;kiểm tra mạch=电路测试=회로 검사;vệ sinh mạch=清洗电路板=기판 세척;sấy=烘干=건조;phủ bảo vệ=保护涂层=보호 코팅;đóng rắn=固化=경화;bôi keo=点胶=디스펜싱;hàn siêu âm=超声波焊接=초음파 용접
Ép nhựa và mạ|ép phun=注塑=사출;khuôn=模具=금형;lòng khuôn=型腔=캐비티;hạt nhựa=塑料颗粒=수지 펠릿;cửa phun=浇口=게이트;ba via=毛边=버;co ngót=收缩=수축;vết lõm=缩水=싱크마크;đường hàn nhựa=熔接线=웰드라인;vệt dòng chảy=流痕=플로마크;mạ=电镀=도금;mạ đồng=镀铜=동도금;mạ niken=镀镍=니켈 도금;mạ vàng=镀金=금도금;bể mạ=电镀槽=도금조;dung dịch=溶液=용액;nồng độ=浓度=농도;tẩy dầu=脱脂=탈지;rửa nước=水洗=수세;sấy sau mạ=镀后烘干=도금 후 건조
Máy và thiết bị|máy=机器=기계;thiết bị=设备=장비;máy nén khí=空压机=공기압축기;bơm=泵=펌프;van=阀门=밸브;xi lanh=气缸=실린더;ống=管=튜브;quạt=风扇=팬;bộ lọc=过滤器=필터;buồng nhiệt=温箱=온도 챔버;buồng nhiệt ẩm=恒温恒湿箱=항온항습기;tủ sấy=烘箱=건조기;máy tính công nghiệp=工业电脑=산업용 컴퓨터;bảng điều khiển=控制面板=제어판;nút bấm=按钮=버튼;màn hình cảm ứng=触摸屏=터치스크린;đèn báo=指示灯=표시등;còi báo=蜂鸣器=부저;bàn xoay=转盘=회전 테이블;trục=轴=축
Vận hành và bảo trì|bật máy=开机=기계 켜기;tắt máy=关机=기계 끄기;khởi động lại=重启=재시작;chế độ tự động=自动模式=자동 모드;chế độ thủ công=手动模式=수동 모드;cài đặt=设置=설정;điều chỉnh=调整=조정;tham số=参数=매개변수;tốc độ máy=机器速度=기계 속도;áp suất=压力=압력;kiểm tra hằng ngày=日常点检=일상 점검;bảo dưỡng=保养=유지보수;bảo trì phòng ngừa=预防性维护=예방 보전;sửa chữa=维修=수리;linh kiện dự phòng=备件=예비 부품;dầu bôi trơn=润滑油=윤활유;thay dầu=换油=오일 교환;rò rỉ=泄漏=누설;tiếng ồn=噪音=소음;rung=振动=진동
Sự cố và xử lý|báo động=报警=알람;lỗi máy=设备故障=장비 고장;ngừng máy=停机=설비 정지;kẹt=卡住=걸림;quá nhiệt=过热=과열;quá tải=过载=과부하;mất điện=停电=정전;đứt dây=断线=단선;lỏng=松动=풀림;không hoạt động=不工作=작동 불량;bất thường=异常=이상;khôi phục=恢复=복구;đặt lại=复位=리셋;kiểm tra lại=复查=재점검;xử lý=处理=처리;nguyên nhân=原因=원인;biện pháp tạm thời=临时措施=임시 조치;biện pháp lâu dài=长期措施=장기 대책;ngăn tái diễn=防止再发生=재발 방지;theo dõi=跟踪=추적 관리
Chất lượng và tiêu chuẩn|đảm bảo chất lượng=质量保证=품질 보증;kiểm soát chất lượng=质量控制=품질 관리;tiêu chuẩn=标准=표준;quy cách=规格=규격;đặc tính=特性=특성;yêu cầu=要求=요구;giới hạn=限值=한계값;giới hạn trên=上限=상한;giới hạn dưới=下限=하한;phạm vi cho phép=允许范围=허용 범위;đạt=合格=합격;không đạt=不合格=불합격;chấp nhận=接受=수락;từ chối hàng=拒收=수입 거부;phê duyệt đặc biệt=特采=특채;hàng lỗi=不良品=불량품;hàng đạt=良品=양품;tỷ lệ lỗi=不良率=불량률;tỷ lệ đạt=合格率=합격률;tỷ lệ đạt lần đầu=一次合格率=직행률
Phương pháp kiểm tra|kiểm tra đầu vào=来料检验=입고 검사;kiểm tra cuối=最终检验=최종 검사;kiểm tra định kỳ=定期检查=정기 검사;kiểm tra lấy mẫu=抽样检验=샘플링 검사;kiểm tra 100 phần trăm=全检=전수 검사;kiểm tra ngoại quan=外观检查=외관 검사;kiểm tra kích thước=尺寸检查=치수 검사;kiểm tra an toàn=安全检查=안전 검사;kiểm tra độ kín=密封检查=기밀 검사;kiểm tra điện áp=电压检查=전압 검사;kiểm tra dòng điện=电流检查=전류 검사;kiểm tra lực=力测试=힘 시험;kiểm tra tuổi thọ=寿命测试=수명 시험;kiểm tra độ bền=强度测试=강도 시험;kiểm tra phá hủy=破坏性试验=파괴 시험;kiểm tra không phá hủy=无损检测=비파괴 검사;mẫu chuẩn=标准样品=표준 샘플;mẫu giới hạn=限度样品=한도 견본;mẫu đầu tiên=首件=초품;mẫu cuối=末件=종품
Đo lường|chiều dài=长度=길이;chiều rộng=宽度=너비;chiều cao=高度=높이;độ dày=厚度=두께;đường kính=直径=직경;bán kính=半径=반경;độ phẳng=平面度=평면도;độ thẳng=直线度=직진도;độ song song=平行度=평행도;độ vuông góc=垂直度=직각도;trọng lượng=重量=무게;thể tích=体积=부피;diện tích=面积=면적;dung sai=公差=공차;độ chính xác=精度=정밀도;độ phân giải=分辨率=분해능;sai số=误差=오차;giá trị thực tế=实际值=실측값;giá trị danh nghĩa=标称值=공칭값;điểm đo=测量点=측정점
Thiết bị đo|thước cặp=卡尺=버니어 캘리퍼스;panme=千分尺=마이크로미터;thước thép=钢尺=철자;đồng hồ so=百分表=다이얼 게이지;thước đo cao=高度尺=하이트 게이지;kính hiển vi=显微镜=현미경;kính lúp=放大镜=확대경;cân=电子秤=전자저울;đồng hồ vạn năng=万用表=멀티미터;máy hiện sóng=示波器=오실로스코프;máy đo 2D=二维测量仪=이차원 측정기;máy đo 3D=三维测量仪=삼차원 측정기;máy đo độ dày=测厚仪=두께 측정기;máy đo lực kéo=拉力计=인장력 측정기;máy đo điện trở=电阻测试仪=저항 측정기;hiệu chuẩn=校准=교정;kiểm chứng=验证=검증;đồ gá đo=测量夹具=측정 지그;chứng chỉ hiệu chuẩn=校准证书=교정 성적서;tem hiệu chuẩn=校准标签=교정 라벨
Lỗi ngoại quan|vết xước=划伤=긁힘;vết nứt=裂纹=크랙;vết bẩn=污渍=얼룩;bám bụi=积尘=먼지 부착;dấu vân tay=指纹=지문;bong tróc=脱落=벗겨짐;bong tách=分层=층간 박리;đổi màu=变色=변색;ố vàng=发黄=황변;rỉ sét=生锈=녹;oxy hóa=氧化=산화;lõm=凹痕=찍힘;phồng=鼓包=부풀음;cong=弯曲=휨;méo=变形=변형;vỡ=破裂=깨짐;sứt=缺口=이빠짐;dính dị vật=异物附着=이물 부착;dấu keo=胶痕=접착제 자국;lệch màu=色差=색차
Lỗi lắp ráp|thiếu linh kiện=缺件=부품 누락;sai linh kiện=错件=부품 오삽;ngược chiều=反向=역방향;lệch vị trí=错位=위치 어긋남;lắp ngược=装反=역조립;lắp sai=错装=오조립;lỏng vít=螺丝松动=나사 풀림;thiếu vít=缺螺丝=나사 누락;tuôn ren=滑牙=나사산 손상;cáp bị kẹp=电缆夹伤=케이블 끼임;đầu nối chưa cắm=连接器未插=커넥터 미삽입;cắm chưa hết=未插到底=불완전 삽입;hàn thiếu=漏焊=미납땜;hàn giả=虚焊=냉땜;chập thiếc=连锡=솔더 브리지;thừa thiếc=锡过多=납 과다;ít thiếc=锡不足=납 부족;linh kiện dựng đứng=立碑=맨해튼 현상;rơi linh kiện=掉件=부품 탈락;đứt mạch=断路=개방 회로
Điện và RF|điện áp=电压=전압;dòng điện=电流=전류;điện trở cách điện=绝缘电阻=절연 저항;điện dung=电容量=정전 용량;tần số=频率=주파수;công suất điện=功率=전력;tín hiệu=信号=신호;độ nhạy=灵敏度=감도;băng thông=带宽=대역폭;độ lợi=增益=이득;nhiễu=干扰=간섭;tiếng nhiễu=噪声=노이즈;kết nối không dây=无线连接=무선 연결;kết nối có dây=有线连接=유선 연결;kết nối Bluetooth=蓝牙连接=블루투스 연결;cổng USB=USB接口=유에스비 포트;nối đất=接地=접지;ngắn mạch=短路=단락;hở mạch=开路=오픈 회로;cực tính=极性=극성
Thử độ tin cậy|thử nhiệt cao=高温试验=고온 시험;thử nhiệt thấp=低温试验=저온 시험;thử nhiệt ẩm=湿热试验=온습도 시험;sốc nhiệt=温度冲击=열충격;chu kỳ nhiệt=温度循环=온도 사이클;thử rung=振动试验=진동 시험;thử rơi=跌落试验=낙하 시험;thử va đập=冲击试验=충격 시험;thử phun muối=盐雾试验=염수 분무 시험;thử lão hóa=老化试验=에이징 시험;thử lưu kho=储存试验=보관 시험;thử vận hành=运行试验=동작 시험;thử uốn=弯折试验=굽힘 시험;thử kéo=拉伸试验=인장 시험;thử bóc=剥离试验=박리 시험;điều kiện thử=试验条件=시험 조건;thời gian thử=试验时间=시험 시간;trước thử=试验前=시험 전;sau thử=试验后=시험 후;ngừng thử=停止试验=시험 중지
An toàn và môi trường|an toàn=安全=안전;nguy hiểm=危险=위험;chú ý=注意=주의;cảnh báo=警告=경고;cấm=禁止=금지;phòng cháy=防火=화재 예방;bình chữa cháy=灭火器=소화기;lối thoát hiểm=安全出口=비상구;sơ tán=疏散=대피;tai nạn=事故=사고;chấn thương=受伤=부상;hóa chất=化学品=화학물질;chất thải=废物=폐기물;nước thải=废水=폐수;khí thải=废气=배기가스;tái chế=回收利用=재활용;tiết kiệm điện=节约用电=절전;tiết kiệm nước=节约用水=절수;sạch sẽ=清洁=청결;vệ sinh=卫生=위생
Bảo hộ và ESD|quần áo bảo hộ=防护服=보호복;mũ bảo hộ=安全帽=안전모;khẩu trang=口罩=마스크;găng tay=手套=장갑;găng chống tĩnh điện=防静电手套=정전기 방지 장갑;kính bảo hộ=护目镜=보안경;giày chống tĩnh điện=防静电鞋=정전기 방지 신발;vòng tay ESD=防静电手环=정전기 방지 손목밴드;thảm ESD=防静电垫=정전기 방지 매트;tĩnh điện=静电=정전기;phóng tĩnh điện=静电放电=정전기 방전;nối đất an toàn=安全接地=안전 접지;khóa an toàn=安全锁=안전 잠금;che chắn=防护罩=안전 커버;thẻ cảnh báo=警示牌=경고 표지;nhãn hóa chất=化学品标签=화학물질 라벨;dụng cụ cách điện=绝缘工具=절연 공구;túi ESD=防静电袋=정전기 방지 봉투;giày bảo hộ=安全鞋=안전화;bịt tai=耳塞=귀마개
Kho và vật tư|kho nguyên liệu=原料仓=원자재 창고;kho thành phẩm=成品仓=완제품 창고;kho bán thành phẩm=半成品仓=반제품 창고;kệ=货架=선반;pallet=栈板=팔레트;xe nâng=叉车=지게차;xe đẩy=推车=대차;phiếu nhập kho=入库单=입고 전표;phiếu xuất kho=出库单=출고 전표;tồn kho an toàn=安全库存=안전 재고;kiểm kê=盘点=재고 실사;chênh lệch tồn=库存差异=재고 차이;vị trí kệ=库位=보관 위치;tồn đầu kỳ=期初库存=기초 재고;tồn cuối kỳ=期末库存=기말 재고;vật tư tồn lâu=呆滞料=장기 재고 자재;thiếu vật liệu=缺料=자재 부족;nhập trước xuất trước=先进先出=선입선출;hạn sử dụng=保质期=사용 기한;điều kiện bảo quản=储存条件=보관 조건
Đóng gói và nhãn|bao bì=包装材料=포장재;thùng carton=纸箱=골판지 상자;hộp nhỏ=小盒=소형 상자;túi nhựa=塑料袋=비닐봉투;túi kín=密封袋=밀봉 봉투;mút đệm=缓冲垫=완충재;túi khí=气泡袋=에어캡;dây đai=打包带=밴딩끈;màng bọc=缠绕膜=스트레치 필름;băng keo đóng thùng=封箱胶带=박스 테이프;nhãn sản phẩm=产品标签=제품 라벨;nhãn thùng=外箱标签=박스 라벨;mã vạch=条形码=바코드;mã QR=二维码=큐알 코드;mã lô=批号=로트 번호;số sê ri=序列号=일련번호;ngày sản xuất=生产日期=제조일;trọng lượng tịnh=净重=순중량;trọng lượng cả bì=毛重=총중량;số lượng đóng gói=包装数量=포장 수량
Xuất hàng và vận chuyển|xe tải=卡车=트럭;container=集装箱=컨테이너;đường bộ=陆运=육상 운송;đường biển=海运=해상 운송;đường hàng không=空运=항공 운송;phí vận chuyển=运费=운송비;ngày giao hàng=交货日期=납품일;ngày xuất hàng=出货日期=출하일;địa chỉ giao hàng=收货地址=배송 주소;người nhận hàng=收货人=수령인;packing list=装箱单=패킹리스트;hóa đơn thương mại=商业发票=상업 송장;vận đơn=提单=선하증권;tờ khai hải quan=报关单=통관 신고서;thông quan=清关=통관;xuất khẩu=出口=수출;nhập khẩu=进口=수입;chuyển phát nhanh=快递=택배;bốc hàng=装货=상차;dỡ hàng=卸货=하차
Mua hàng và nhà cung cấp|nhà cung cấp=供应商=공급사;báo giá=报价=견적;đơn giá=单价=단가;tổng giá=总价=총액;chi phí=费用=비용;ngân sách=预算=예산;thanh toán=付款=결제;hóa đơn=发票=계산서;hợp đồng=合同=계약;điều khoản=条款=조항;thời gian cung ứng=交期=리드타임;số lượng tối thiểu=最小订购量=최소 주문 수량;đặt hàng=下单=주문하다;hủy đơn=取消订单=주문 취소;đặt hàng bổ sung=追加订单=추가 주문;đơn đặt mua=采购订单=구매 주문서;hàng miễn phí=免费品=무상 제품;mẫu miễn phí=免费样品=무상 샘플;hàng trả lại=退货=반품;chi phí thay thế=更换费用=교체 비용
Khách hàng và phản hồi|khách hàng=客户=고객;nhu cầu khách hàng=客户需求=고객 요구;phản hồi=反馈=피드백;khiếu nại=投诉=클레임;trả lời=回复=회신;thăm nhà máy=参观工厂=공장 방문;đánh giá nhà cung cấp=供应商评价=공급사 평가;phê duyệt mẫu=样品承认=샘플 승인;thông số kỹ thuật=技术规格=기술 사양;thỏa thuận=协议=합의;hỗ trợ kỹ thuật=技术支持=기술 지원;bảo hành=保修=보증;đổi trả=换货=교환;sửa lỗi=修正=수정;cam kết=承诺=약속;xác nhận lịch=确认日程=일정 확인;người đầu mối=对接人=창구 담당자;yêu cầu thay đổi=变更要求=변경 요청;mức hỗ trợ=支持范围=지원 범위;ngày phản hồi=回复日期=회신일
Tài liệu và dữ liệu|tài liệu=文件=문서;hồ sơ=记录=기록;biểu mẫu=表格=양식;danh sách=清单=목록;báo cáo=报告=보고서;bản vẽ=图纸=도면;quy trình=流程=절차;hướng dẫn=说明=안내;phiên bản=版本=버전;sửa đổi=修订=개정;bản gốc=原件=원본;bản sao=副本=사본;bản mới nhất=最新版=최신 버전;bản cũ=旧版=구버전;dữ liệu gốc=原始数据=원시 데이터;tệp đính kèm=附件=첨부 파일;thư mục=文件夹=폴더;tên tệp=文件名=파일명;đường dẫn=路径=경로;quyền truy cập=访问权限=접근 권한
Máy tính và ứng dụng|máy tính=电脑=컴퓨터;bàn phím=键盘=키보드;chuột=鼠标=마우스;màn hình máy tính=显示器=모니터;máy in=打印机=프린터;máy quét=扫描仪=스캐너;mạng=网络=네트워크;Internet=互联网=인터넷;tài khoản=账号=계정;mật khẩu=密码=비밀번호;đăng nhập=登录=로그인;đăng xuất=退出登录=로그아웃;tải xuống=下载=다운로드;tải lên=上传=업로드;lưu tệp=保存文件=파일 저장;sao lưu=备份=백업;khôi phục dữ liệu=数据恢复=데이터 복구;phần mềm=软件=소프트웨어;phần cứng=硬件=하드웨어;cập nhật=更新=업데이트
Họp và liên lạc|cuộc họp=会议=회의;họp sáng=早会=조회;họp tuần=周会=주간 회의;họp trực tuyến=线上会议=온라인 회의;lời mời=邀请=초대;người tham dự=参会者=참석자;nội dung họp=会议内容=회의 내용;biên bản họp=会议纪要=회의록;chủ đề=主题=주제;ý kiến=意见=의견;đề xuất=提案=제안;kết luận=结论=결론;quyết định=决定=결정;việc cần làm=待办事项=할 일;hạn hoàn thành=截止时间=마감 기한;điện thoại=电话=전화;email=电子邮件=이메일;tin nhắn=消息=메시지;cuộc gọi=通话=통화;họp lại=再次开会=재회의
Audit và cải tiến|đánh giá nội bộ=内部审核=내부 심사;đánh giá bên ngoài=外部审核=외부 심사;đoàn đánh giá=审核组=심사팀;bằng chứng=证据=증거;điểm không phù hợp=不符合项=부적합 사항;hành động khắc phục=纠正措施=시정 조치;hành động phòng ngừa=预防措施=예방 조치;phân tích nguyên nhân gốc=根因分析=근본 원인 분석;truy xuất=追溯=추적성;kiểm soát thay đổi=变更控制=변경 관리;quản lý rủi ro=风险管理=위험 관리;kế hoạch hành động=行动计划=실행 계획;đánh giá hiệu quả=效果评价=효과 평가;cải tiến liên tục=持续改进=지속적 개선;đào tạo=培训=교육;hồ sơ đào tạo=培训记录=교육 기록;chữ ký=签名=서명;con dấu công ty=公司印章=회사 직인;đóng dấu=盖章=날인;phê duyệt=批准=승인
Báo cáo kết quả|kết quả=结果=결과;tình hình=情况=상황;hiện trạng=现状=현황;tóm tắt=摘要=요약;chi tiết=详情=상세 내용;số liệu=数据资料=수치 자료;biểu đồ=图表=차트;bảng=表=표;ảnh=照片=사진;video=视频=동영상;so sánh=比较=비교;xu hướng=趋势=추세;trung bình=平均=평균;lớn nhất=最大=최대;nhỏ nhất=最小=최소;tổng cộng=总计=합계;lũy kế=累计=누계;hạng mục=项目=항목;nhận xét=评价=평가;kết quả cuối=最终结果=최종 결과
Bàn giao và đào tạo|bàn giao=交接=인계;tiếp nhận=接收=인수;người mới=新人=신입;người hướng dẫn=指导人员=지도자;học việc=实习=실습;hướng dẫn thao tác=操作指导=작업 지도;đào tạo tại chỗ=现场培训=현장 교육;thực hành=练习=연습;kiểm tra hiểu biết=理解度检查=이해도 점검;tài liệu bàn giao=交接文件=인계 문서;việc chưa xong=未结事项=미결 사항;đầu việc=工作事项=업무 항목;tiến độ bàn giao=交接进度=인계 진행 상황;người tiếp nhiệm=接任者=후임자;bàn giao ca=交班=근무 인계;sổ bàn giao=交接本=인계 일지;địa điểm lưu=保存位置=저장 위치;thông tin liên hệ=联系方式=연락처;đánh giá đào tạo=培训评价=교육 평가;kế hoạch đào tạo=培训计划=교육 계획
5S và sắp xếp|sàng lọc=整理=정리;sắp xếp=整顿=정돈;quét dọn=清扫=청소;duy trì sạch=清洁保持=청결 유지;kỷ luật=纪律=규율;vạch kẻ=标线=구획선;đánh dấu=标识=표시;vùng để đồ=放置区域=적치 구역;thùng rác=垃圾桶=쓰레기통;rác thường=一般垃圾=일반 쓰레기;rác tái chế=可回收垃圾=재활용 쓰레기;thu gom=收集=수거;phân loại=分类=분류;đồ không dùng=不用物品=불용품;vật dụng cá nhân=个人物品=개인 물품;khu công cộng=公共区域=공용 구역;sàn=地板=바닥;tường=墙=벽;cửa sổ=窗户=창문;sạch bụi=除尘=먼지 제거
Ăn uống và sinh hoạt|nước uống=饮用水=식수;nước nóng=热水=뜨거운 물;nước lạnh=冷水=찬물;cơm=米饭=밥;bữa sáng=早餐=아침 식사;bữa trưa=午餐=점심 식사;bữa tối=晚餐=저녁 식사;thức ăn=食物=음식;cà phê=咖啡=커피;trà=茶=차;cốc=杯子=컵;đũa=筷子=젓가락;thìa=勺子=숟가락;khay cơm=餐盘=식판;thực đơn=菜单=메뉴;căng tin=小卖部=매점;đói=饿=배고프다;khát=渴=목마르다;mệt=累=피곤하다;bận=忙=바쁘다
Thời tiết và đi lại|mưa=下雨=비가 오다;nắng=晴天=맑은 날;gió=风=바람;nóng=热=덥다;lạnh=冷=춥다;xe buýt=公交车=버스;xe đưa đón=班车=통근 버스;xe máy=摩托车=오토바이;ô tô=汽车=자동차;taxi=出租车=택시;ga tàu=火车站=기차역;sân bay=机场=공항;tắc đường=堵车=교통 체증;đến nơi=到达=도착;khởi hành=出发=출발;đón=接=마중;đưa về=送回=데려다주다;địa chỉ=地址=주소;bản đồ=地图=지도;lịch trình di chuyển=行程=이동 일정
Tính chất sản phẩm|cứng=硬=단단하다;mềm=软=부드럽다;dày=厚=두껍다;mỏng=薄=얇다;nặng=重=무겁다;nhẹ=轻=가볍다;chặt=紧=꽉 끼다;lỏng lẻo=松=헐겁다;khô=干=마르다;ướt=湿=젖다;trơn=光滑=매끄럽다;nhám=粗糙=거칠다;trong suốt=透明=투명하다;đục=不透明=불투명하다;dính=粘=끈적하다;sắc=锋利=날카롭다;mòn=磨损=마모;độ đàn hồi=弹性=탄성;độ cứng=硬度=경도;độ bền=强度=강도
Từ nối và câu hỏi|tại sao=为什么=왜;như thế nào=怎么=어떻게;cái gì=什么=무엇;ai=谁=누구;khi nào=什么时候=언제;bao nhiêu=多少=얼마;ở đâu=在哪里=어디에서;cái nào=哪一个=어느 것;bởi vì=因为=왜냐하면;vì vậy=所以=그래서;nhưng=但是=하지만;và=和=그리고;hoặc=或者=또는;nếu=如果=만약;trước khi=之前先=하기 전에;sau khi=之后再=한 후에;trong khi=期间=하는 동안;mặc dù=虽然=비록;ngoài ra=另外=추가로;tuy nhiên=然而=그러나
Động từ công việc|sử dụng=使用=사용하다;chuẩn bị=准备=준비하다;hoàn tất=结束=마치다;tiếp tục=继续=계속하다;dừng lại=停止=중지하다;vận hành=操作=조작하다;kiểm tra=检查=검사하다;đo=测量=측정하다;ghi chép=记录下来=기록하다;tính toán=计算=계산하다;thay thế=替换=교체하다;sắp đặt=安排=배치하다;đóng gói=包装=포장하다;vận chuyển=运输=운송하다;sửa=修理=수리하다;vệ sinh=清洗=세척하다;siết=拧紧=조이다;nới lỏng=拧松=풀다;cắt=切割=자르다;dán=粘贴=붙이다
Động từ dữ liệu và quản lý|lập báo cáo=写报告=보고서를 작성하다;gửi email=发邮件=이메일을 보내다;sao chép=复制=복사하다;lưu trữ=存档=보관하다;xóa=删除=삭제하다;tìm kiếm=查找=검색하다;đối chiếu=核对=대조하다;duyệt xét=审核=검토하다;phê duyệt văn bản=审批=결재하다;chia sẻ=共享=공유하다;đăng ký=登记=등록하다;in=打印=인쇄하다;quét mã=扫码=코드를 스캔하다;nộp=提交=제출하다;bổ sung=补充=보충하다;chỉnh sửa=修改=수정하다;gia hạn=延长=연장하다;hủy=取消=취소하다;xác minh=核实=확인 검증하다;đặt lịch=预约=예약하다
Tình trạng công việc|đang chờ=等待中=대기 중;đang xử lý=处理中=처리 중;đã hoàn thành=已完成=완료됨;chưa kiểm tra=未检查=미검사;đã kiểm tra=已检查=검사 완료;chờ phê duyệt=待批准=승인 대기;tạm giữ=暂扣=보류;đã phát hành=已发行=발행 완료;đã hủy=已取消=취소됨;đã giao=已交付=납품 완료;chưa nhập kho=未入库=미입고;đã nhập kho=已入库=입고 완료;chưa xuất kho=未出库=미출고;đã xuất kho=已出库=출고 완료;chưa nhận=未收到=미수령;đã nhận=已收到=수령 완료;đang thiếu=短缺=부족 상태;đã bổ sung=已补充=보충 완료;đã khôi phục=已恢复=복구 완료;đang theo dõi=跟踪中=추적 중'''

def root_entries():
 out=[]
 for line in RAW.splitlines():
  category,values=line.split('|')
  for v in values.split(';'):
   vi,zh,ko=v.split('=');out.append((category,vi,zh,ko))
 return out

# These compounds are standard workplace noun groups, kept with Vietnamese meanings.
# The subject/property pair is chosen by context; no random Cartesian product.
COMPOUNDS=[
('Vật liệu / sản phẩm',[
('vật liệu','物料','자재'),('nguyên liệu','原材料','원자재'),('linh kiện','零部件','부품'),('bán thành phẩm','半成品','반제품'),('thành phẩm','成品','완제품'),('sản phẩm lỗi','不良品','불량품'),('hàng trả lại','退货品','반품품'),('mẫu thử','试验样品','시험 샘플'),('hàng giao','交付产品','납품 제품'),('bao bì','包装材料','포장재'),('sản phẩm mới','新产品','신제품'),('hàng thay thế','替代品','대체품'),('hàng nhập','入库物料','입고 자재'),('hàng xuất','出库物料','출고 자재'),('mẫu đầu','首件样品','초품 샘플')],[
('số lượng','数量','수량'),('mã','编码','코드'),('danh sách','清单','목록'),('tình trạng','状态','상태'),('vị trí lưu','存放位置','보관 위치'),('hồ sơ','记录','기록'),('lô','批次','로트'),('tiêu chuẩn kiểm tra','检验标准','검사 기준'),('ngày nhận','接收日期','수령일'),('nhãn','标签','라벨'),('chi phí','费用','비용'),('thông tin','信息','정보')]),
('Quản lý quy trình',[
('sản xuất','生产','생산'),('lắp ráp','装配','조립'),('đóng gói','包装','포장'),('kiểm tra','检验','검사'),('xuất hàng','出货','출하'),('nhập kho','入库','입고'),('xuất kho','出库','출고'),('bảo trì','维护','보전'),('sửa chữa','维修','수리'),('hiệu chuẩn','校准','교정'),('đào tạo','培训','교육'),('thử nghiệm','试验','시험'),('đánh giá','审核','심사'),('sàng lọc','筛选','선별'),('làm lại','返工','재작업'),('mua hàng','采购','구매'),('bàn giao','交接','인계'),('vận chuyển','运输','운송'),('cải tiến','改善','개선'),('thay đổi','变更','변경')],[
('kế hoạch','计划','계획'),('lịch','日程','일정'),('thời gian','时间','시간'),('kết quả','结果','결과'),('báo cáo','报告','보고서'),('người phụ trách','负责人','담당자'),('quy trình','流程','절차'),('hồ sơ','记录','기록'),('chi phí','费用','비용'),('tiến độ','进度','진행 상황'),('yêu cầu','要求','요구 사항'),('trạng thái','状态','상태')]),
('Thiết bị / công cụ',[
('thiết bị','设备','장비'),('máy','机器','기계'),('đồ gá','夹具','지그'),('thiết bị đo','测量设备','측정 장비'),('khuôn','模具','금형'),('dụng cụ','工具','공구'),('máy in','打印机','프린터'),('máy quét mã','扫码器','코드 스캐너'),('buồng nhiệt ẩm','恒温恒湿箱','항온항습기'),('máy nén khí','空压机','공기압축기')],[
('mã','编号','번호'),('tình trạng','状态','상태'),('vị trí','位置','위치'),('danh sách','清单','목록'),('hồ sơ','记录','이력'),('kiểm tra hằng ngày','日常点检','일상 점검'),('hướng dẫn sử dụng','使用说明','사용 설명서'),('người phụ trách','负责人','담당자'),('chi phí sửa chữa','维修费用','수리 비용'),('kế hoạch bảo trì','维护计划','보전 계획')]),
('Chất lượng và hồ sơ',[
('IQC','来料检验','입고 검사'),('OQC','出货检验','출하 검사'),('kiểm tra ngoại quan','外观检查','외관 검사'),('kiểm tra kích thước','尺寸检查','치수 검사'),('thử RF','射频测试','알에프 시험'),('thử chức năng','功能测试','기능 시험'),('thử độ tin cậy','可靠性试验','신뢰성 시험'),('kiểm tra lấy mẫu','抽样检验','샘플링 검사'),('kiểm tra toàn bộ','全数检验','전수 검사'),('kiểm tra mẫu đầu','首件检验','초품 검사')],[
('tiêu chuẩn','标准','기준'),('kết quả','结果','결과'),('báo cáo','报告','보고서'),('hồ sơ','记录','기록'),('số lượng mẫu','样品数量','샘플 수량'),('lịch','日程','일정'),('người phụ trách','负责人','담당자'),('địa điểm','地点','장소'),('tiến độ','进度','진행 상황'),('điều kiện','条件','조건')])]

def entries(language):
 rows=[]
 for cat,vi,zh,ko in root_entries():rows.append(dict(category=cat,h=zh if language=='zh' else ko,v=vi,kind='word'))
 for cat,subjects,properties in COMPOUNDS:
  for vi_s,zh_s,ko_s in subjects:
   for vi_p,zh_p,ko_p in properties:
    rows.append(dict(category=cat,h=zh_s+zh_p if language=='zh' else ko_s+' '+ko_p,v=vi_p+' '+vi_s,kind='phrase'))
 return rows
